### ISSUE TITLE
Ignore zeroed data

### ISSUE THREAD

**Issue by Nefelim4ag** [markfasheh/duperemove#106]
as you know, duperemove take too long time to compute duplicated extents in sparse data, like:
truncate -s 4G {1..3}
duperemove -hrd {1..3}

I think, what in that case, option like --ignore=zeroed
Can speedup deduping phase.

**Comment by markfasheh** [comment]
Well there's this code in find_dupes.c which is attempting this:

#define SKIP_FLAGS	(FILE_BLOCK_SKIP_COMPARE|FILE_BLOCK_HOLE)

	list_for_each_entry(block1, &dups->dl_list, b_list) {
		if (block1->b_flags & SKIP_FLAGS)
			continue;

csum_next_block() file_scan.c is responsible for setting these flags based on an optional fiemap call but if you look at the code, the required fiemap context is never passed through.

Could you try the patch in issue106 branch (remember to pass --lookup-extents=yes) and let me know if it helps? Btw this should also fix your example problem in issue107.

**Comment by Nefelim4ag** [comment]
Thanks, i will try implement it
---
P.S. Sorry for long reaction

**Comment by Nefelim4ag** [comment]
Merged, thanks
