### ISSUE TITLE
very high ram usage

### ISSUE THREAD

**Issue by thorus90** [markfasheh/duperemove#11]
Hi,

I'm deduping very big files (~8GB) but not very many (~80) with block-size 4k. In sum it is 500G. With an hash of 256bit per 4k the hashes take round about 4GB.

Right now I need ~15GB RAM. 

I guess duperemove holds the hole file in the ram and then does the striping in the blocks and building the hashes? If so, it would be great if duperemove reads the file partial, so there is no problem with big files.

Another really nice thing would be, if it stores the hashes on the disk, so I can resume the process. (The data is never changing, to be exact its an archive). Without that I have no chance to dedup the whole archive (which would be amazing, cause I hope there is much space to save :) )

Thanks for an answer.

**Comment by clobrother** [comment]
markf merged a code that reduce memory usage, you should try it (use the --write-hashes option)

**Comment by frell** [comment]
--write-hashes has been a great improvement.

 However  im still noticing this issue when duperemove comes across a very large single file (>20Gb). 

It would be awesome if there was a "--max-filesize x" option which made duperemove skip files larger than x

**Comment by clobrother** [comment]
Wild, are not you confusing with IO cache ?
Anyway, you can do what you want using find & a pipe, something like that : 
```
find -type f -size -20G | duperemove -
```

**Comment by frell** [comment]
Thank you, but wont that just exceed the max input variables when performed on a large folder.

**Comment by clobrother** [comment]
Are you using the line I wrote ?
That error should be raised if you do something like that : 
```
duperemove *
```

However, using a pipe and a dash as a filelist, the file list will be read from stdin, your shell will not expand anything, and thus will not raise an error

Please, check your command or post it

**Comment by frell** [comment]
@clobrother - You're 100% right. Sorry and thank you for the tip.
