### ISSUE TITLE
Dedup read-only <-> read-write files/subvolumes

### ISSUE THREAD

**Issue by sherter** [markfasheh/duperemove#112]
I don't know how deduplication works internally, so please apologize if this is a totally stupid question.

Why is it not possible to deduplicate files _A_ and _B (and C, D,...)_ , where _A_ is on a _read-only_ snapshot and _B (and C, D, ...)_ is in on a _read-write_ subvolume? Why can't I only change _B_ to use some or all blocks from _A_?

The use case is that I have a bunch of deduplicated backups on one drive and I now want to start using btrfs send/receive from another drive. Incremental send/receive works only with read-only snapshots (as far as I know?). My idea is to do a non-incremental send/receive once, deduplicate the existing backups against this 'seed' snapshot and from that point on do incremental send/receive backups.

**Comment by danc86** [comment]
`duperemove` will happily run against read-only btrfs snapshots. You probably have to use the `-A` option (and run as root).

**Comment by markfasheh** [comment]
-A is the correct answer here. Closing for now.

**Comment by avidseeker** [comment]
Can't find this flag in the documentation. It currently results in an error.

```
$ duperemove -drA --hashfile hash.hash ./
duperemove: invalid option -- 'A'
```
