### ISSUE TITLE
Lack of documented functions

### ISSUE THREAD

**Issue by Wintch** [markfasheh/duperemove#113]
Hi,

In the performance test on this page: https://github.com/markfasheh/duperemove/wiki/Performance-Numbers an example of using this switches is given:

--read-hashes
--write-hashes

I am using duperemove v0.10 and would really appreciate those "hidden" switches to be explained in "--help" output. There is an option to "update_hashes" in duperemove.c, does it work?

Thanks for the tool!

**Comment by lpirl** [comment]
Did you see [the documentation about `--*-hashes`](https://github.com/markfasheh/duperemove/blob/7367a3c8446a71c13bfbc01eec646a8b4f2c07d1/duperemove.8#L132-L147) in the man page?

**Comment by Wintch** [comment]
Sorry, i missed that, update_hashes is not in man, so my grep failed :) This is not something stable, right? I would like to reuse the hash file and not generate a new one each time for dedup. Thanks!

**Comment by lpirl** [comment]
\<IIRC\> It is more or less deprecated but might still be used for development. It uses plain text files to store hashes and some magic to detect dupes and so on. There is the newer `--hashfile=<path>` that creates (and for subsequent runs: _re-uses_) a SQLite database. \</IIRC\>

**Comment by Wintch** [comment]
Thanks!
