### ISSUE TITLE
Memory usage (Wiki prominence)

### ISSUE THREAD

**Issue by chriswyatt** [markfasheh/duperemove#116]
Hi,

Thanks for your great tool. Currently using it to deduplicate my hard drive. I read the Wiki page before running the tool, but there was no mention of the high memory usage. The GUI in my VM has completely locked up, presumably due to duperemove consuming nearly all its allocated memory (2 GB). If I had known this, I could have given the VM more memory beforehand; however it's too late to start it again now I think.

I think it would be handy to mention this on the Wiki, in a prominent location.

Sorry if 'issues' isn't really the right place for this, but I couldn't find anywhere for general feedback.

Thanks,

Chris

**Comment by lpirl** [comment]
Did you use the `--hashfile` option?
IIRC and from what I saw when I occasionally checked on the corresponding machine, using `--hashfile`and a block site of 128k, there was maybe around 2GB of memory usage for deduplicting 3.5TB of data. Personally, I'd consider this memory usage alright.

**Comment by chriswyatt** [comment]
The memory usage is fine, and my PC has 16 GB, so plenty of leg room. I just don't tend to give my VMs much, because they usually don't need much for what I use them for. Something like a table showing estimated memory usage for different file system sizes, would have caught my attention.

**Comment by lpirl** [comment]
Although I am not too deep into this, the memory usage might depend on a variety of factors: file system usage, number of files, amount of duplicate data, block size, …
If you are willing to contribute your experiences and start such a table, that's great!

**Comment by chriswyatt** [comment]
Meh. I'll just close this. I only opened this to help other users, but I sense resistance, and it's not worth the effort.

**Comment by lpirl** [comment]
Oh sorry, I hope you did not get me wrong: More detailed documentation is definitely desirable.
Duperemove is – besides valuable contributions – basically a one-man-show (thanks @markfasheh) and we cannot expect him to do what we want.
However, if someone contributes documentation like you suggest, all users profit – it's still a very good suggestion IMHO.

**Comment by chriswyatt** [comment]
No worries. I was aware of the --hashfile option, and that should have been a clue to the app being memory intensive. From your first reply I had also thought you'd got the wrong end of the stick.

Yes, more documentation is a good thing, and it helps idiots like me. I'm not the best person to start a table as I know little about the script -- I'm just a user.

**Comment by markfasheh** [comment]
Hey I'll leave this open and tagged so when I get a chance I can update the docs. This is exactly the type of situation that --hashfile is supposed to help, so if it wasn't obvious that was what you should do, we ought to make it so (as Lukas mentions).

My initial thought is to update the man page in a couple locations, making --hashfile more prominent. Perhaps putting it in the synopsis and adding a 'Hashfiles' section under 'GENERAL' might do it.

**Comment by vandenoever** [comment]
I'm a happy user of duperemove. I'm providing some information on my use of dupremove. I'm using it to dedupe data on 4TB harddisk with one btrfs partition. The machine has 4GB of memory. I'm using the --hashfile option. The memory use of duperemove is about 2GB and the hashfile grows to about 1GB. Running duperemove on such a large disk can take half a day to a day. The disk contains a lot of duplicate data, so the savings are very large.

A way to speed up duperemove for subsequent invocations might be to store size, mtime and hash in the hashfile and not recalculate the hash on subsequent runs when size and mtime are unchanged.

**Comment by ikrabbe** [comment]
I generally wonder about the memory usage of 2GByte. This seems far too much for me. I run this to reduce space for historic mysql dumps and I currently have a hashfile of 1.5GByte.
Where is this 2GByte Pool used in the duperemove process and for what?

**Comment by clobrother** [comment]
Can you give me your command line ?
Is this behavior still happening in the last code ?

**Comment by ikrabbe** [comment]
`duperemove -b 4k -r --hashfile /dupe.hash -d last archive/[0-9]* >>/tmp/dump_dbs.out`

This is a duperemove v0.10 from a binary package in a centos7... I just evaluate the useability for my prupose.

**Comment by markfasheh** [comment]
Hi, can you tell me what your memory usage is like with the '-b 4k' option taken out (or change it to '-b 128k')? Thanks

**Comment by markfasheh** [comment]
@vandenoever thanks for your usage information, if you check out the master branch I've implemented the mtime feature you requested. It (or something along those lines) has been on my todo list for a while now so thanks for the motivation. Please test and file bugs, documentation is a work in progress.

**Comment by markfasheh** [comment]
I added an item to my release checklist:
https://github.com/markfasheh/duperemove/wiki/Release-Checklist

So once that's ticked off I'll close this bug.

**Comment by vandenoever** [comment]
@markfasheh sure, what cmdline options would you like me to check with?
Btw, such a run takes a few days and to see if there's a speedup, I need to do two or three runs.

**Comment by markfasheh** [comment]
@vandenoever 
Get the latest code from master branch and build it as is typical. Then run it like you normally do:

Say hashfile=data.hash and the directory to dedupe is in /data:

duperemove --hashfile=data.hash -rdvh /data

Keep data.hash around and run again with the same exact command:

duperemove --hashfile=data.hash -rdvh /data

The 2nd time we'll crawl /data as usual but use the database in data.hash to figure out which files are new and which ones have changed. We will only scan new or changed files so the 2nd run should  be far faster than the first. data.hash of course gets updated with the latest hashes. If it no longer finds a file that is in the db, that file is dropped from data.hash.

If you want to add new paths to the db that were outside of /data, just add them to the command line (this assumes /data and /newdata are on the same fs):

duperemove --hashfile=data.hash -rdvh /data /newdata


Finally, if you wanted to update the hashes but without crawling the fs (so we won't discover new files but changed and deleted ones will be updated in our db and deduped) just run without the files argument:

duperemove --hashfile=data.hash -rdvh


Also, you should be able to interrupt (ctrl-c) duperemove at any time now and reuse that hashfile without fear of corrupting the database and with duperemove picking up where it left off.

Lastly thanks in advance for testing this it will really help a lot to see what issues you may encounter as it's relatively fresh code.

**Comment by markfasheh** [comment]
Closing for now as I have updated the man page with information on how to calculate memory usage, as well as hash file size.
