### ISSUE TITLE
show progress when doing dedupe

### ISSUE THREAD

**Issue by vandenoever** [markfasheh/duperemove#119]
After scanning, when doing deduplication, many messages like this are shown:
```
Try to dedupe extents with id ff4a9...
```
Presumably, the number of tries that will be performed is known, so the line could show progress as [920/34289 in 3h20m] or [5.5% in 3h20m].
Such information might help with guessing how long the deduplication process will take.

**Comment by markfasheh** [comment]
I added a simple count in master branch - we can get fancier in a future patch if need be. Thanks for the suggestion!
