### ISSUE TITLE
Can't dedup extents in same file

### ISSUE THREAD

**Issue by Nefelim4ag** [markfasheh/duperemove#12]
"houston we have a problem" (this problem on performance-wip brunch too)
I think this is not expected behaviour:
I create file:
$ truncate -s 1M ~/lol
or
$ dd if=/dev/urandom of=/tmp/lol bs=128k count=1 && for i in `seq 0 7`; do ; cat /tmp/lol >> ~/lol ; done
$ sudo duperemove --debug -hrd ~/lol
Using 128K blocks
csum: /home/timofey/lol
Block hash tree has 1 hash nodes and 8 block items
All blocks with hash: fa43239bcee7b97ca62f007cc68487560a39e19f74f3dde7486db3f98df8e471
/home/timofey/lol2      loff: 0 lblock: 0 seen: 0
/home/timofey/lol2      loff: 131072 lblock: 1 seen: 0
/home/timofey/lol2      loff: 262144 lblock: 2 seen: 0
/home/timofey/lol2      loff: 393216 lblock: 3 seen: 0
/home/timofey/lol2      loff: 524288 lblock: 4 seen: 0
/home/timofey/lol2      loff: 655360 lblock: 5 seen: 0
/home/timofey/lol2      loff: 786432 lblock: 6 seen: 0
/home/timofey/lol2      loff: 917504 lblock: 7 seen: 0
Hashed 8 blocks. Calculating duplicate extents - this may take some time.
Simple read and compare of file data found 0 instances of extents that might benefit from deduplication.

Removing overlapping extents

Simple read and compare of file data found 0 instances of extents that might benefit from deduplication.
Nothing to dedupe.

But if i create 2 same files they will be deduped correctly.

P.S. i don't know how to cover this nicely, as example:
1. Create rb tree for file with hashes
2. Dedup him -> clean or recreate # for when we store duplicate extends if we can delete him from tree?
3. Merge master rb tree with file rb tree.
And cover it case like compress utilities algorithm -e extreme dedup %) (as i understand it very slowdown duperemove util)

**Comment by Edoa** [comment]
Sigh ... 
Is this still true after almost a year?
My application is an iscsi host. Inside a big iscsi file there are several virtual machine disks. Can I dedupe them?
The workaround suggested by @Nefelim4ag works too if I run duperemove on both this file and his snapshot?
Someone has made some tests?

**Comment by markfasheh** [comment]
FYI all, I have a patch series out to the btrfs list which adds this feature (amongst others):

http://www.spinics.net/lists/linux-btrfs/msg44956.html

We'll need to update duperemove as well but I don't think that should be particularly difficult.

**Comment by CyberShadow** [comment]
> My application is an iscsi host. Inside a big iscsi file there are several virtual machine disks. Can I dedupe them?

Not sure what the status of this is, but I wrote a simple utility that uses the clone-range ioctl to copy a file while deduplicating it:
http://dump.thecybershadow.net/3391be965b190d9f9d07cdc2f0a02197/cp-btrfs-dedup.d

**Comment by markfasheh** [comment]
So this works fine in duperemove but btrfs has a bug where fiemap spins for an extremely long time when checking whether an extent is shared or not. As a result same-file dedupe is disabled by default until we have a patch to fix btrfs. If you wish to try it despite the possible issue in btrfs just run with --dedupe-options=same.
