### ISSUE TITLE
duperemove stalls in final phase...

### ISSUE THREAD

**Issue by daviddelikat** [markfasheh/duperemove#123]
I ran duperemove with about 4T of files to scan...  it hashed all the files ( 200,000+ ) a processed a large number of them for duplicate extents; submitted many of them for deduplication; then stalled for probably 12 hours before I hit ctrl-C to stop it.  it had consumed about 8G of RAM and released all of it when I hit ctrl-C but it has not exitted.  I expect that it has lots of cleanup to do so I am not (yet) worried about the continuing process, I am wondering if there may be some limits in the kernel or elsewhere that I have reached which caused it to stall?  I'm thinking perhaps there is a limit on the number of duplicate extents that can be submitted ( a memory limit I'd think ) and perhaps there is some delay or other restriction in how they get processed?  once the process exits I will try running it on a smaller piece of the drive and see how it works.  I'll post a status if/when it completes.

**Comment by daviddelikat** [comment]
well, I killed the duperemove process completely ( it was defunct ) and I cannot access the file system...

**Comment by markfasheh** [comment]
Huh, it sounds like btrfs is hung up on something. What kernel are you running? There was a ->readpage / dedupe deadlock we fixed a couple releases ago which you might be hitting. How much of the FS is inaccesible?

**Comment by daviddelikat** [comment]
'uname -a'  gives:
Linux server1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
when it first locked up I was just 'ls'ing the root of the btrf file system...  I decided to reboot and found everything came back fine.  I'm assuming that I pushed duperemove past some ( possibly reasonable ) boundary.  I'm just going to run it on smaller pieces where I expect to find duplicates.  If there is anything I can do that might locate a real issue, let me know.  I'm very pleased that my btrfs file system seems to have survived this process without any loss of data.

**Comment by markfasheh** [comment]
Ok, you'll want this commit from Linux v4.3:
    293a848 btrfs: fix clone / extent-same deadlocks

I am very confident that it fixes the deadlock you're seeing. Feel free to re-open if you have troubles with it, or just further questions.

**Comment by markfasheh** [comment]
A better link for you:

https://github.com/torvalds/linux/commit/293a848
