### ISSUE TITLE
Man page seems a bit outdated

### ISSUE THREAD

**Issue by tgharib** [markfasheh/duperemove#138]
According to the man page:

       --hashfile=hashfile
              Use  a  file for temporary storage of hashes instead of memory. This option drastically reduces the memory footprint
              of duperemove and is recommended when your data set is more than a few files large. If the hashfile exists, it  will
              be overwritten. The hashfile can be deleted when duperemove is complete.

              A  future enhancement will allow duperemove to reuse the data inside hashfiles to optimize the file scan by skipping
              unchanged files.

But according to the README:

`Duperemove can store the hashes it computes in a hashfile. If given an existing hashfile, duperemove will only compute hashes for those files which have changed since the last run. Thus you can run duperemove repeatedly on your data as it changes, without having to re-checksum unchanged data.`

So it seems the man page is outdated.

**Comment by markfasheh** [comment]
What version are you reading the manpage from? Master (v0.11) has this change:

https://github.com/markfasheh/duperemove/commit/251fd5af90f71354e65f317d8c1ddd85acbc21c6

**Comment by tgharib** [comment]
Opps, this was my own stupidity. I had duperemove v0.10 installed.
