### ISSUE TITLE
duperemove dedupe results in btrfs-check reporting errors

### ISSUE THREAD

**Issue by dcartt** [markfasheh/duperemove#141]
Running duperemove with the dedupe option appears to cause file system metadata problems, at least according to btrfs-check.  This only happens if duperemove finds some minimal amount of deduplication to do. In other words, if duperemove finds nothing or only a few things to dedupe then no errors are reported.  Many of the errors remain after running btrfs-check with the repair option.  

duperemove v0.11.beta1
btrfs-progs v4.7
4.7.0 kernel, x64

Attached is the output from btrfs-check after deduplication, for the repair, and after the repair.  Also attached is the duperemove dedupe output.  The test is easily repeatable starting from a file system with no btrfs-check errors.

[btrfs-check.after_duperemove.output.txt](https://github.com/markfasheh/duperemove/files/431519/btrfs-check.after_duperemove.output.txt)
[btrfs-check.after_repair.output.txt](https://github.com/markfasheh/duperemove/files/431520/btrfs-check.after_repair.output.txt)
[btrfs-check.repair.output.txt](https://github.com/markfasheh/duperemove/files/431521/btrfs-check.repair.output.txt)
[duperemove.dedupe.output.tar.gz](https://github.com/markfasheh/duperemove/files/431522/duperemove.dedupe.output.tar.gz)

**Comment by markfasheh** [comment]
Hmm it looks like some ref counts are getting messed up. I'll do this on my end, and see if I can reproduce (sounds like it should be easy).

**Comment by dcartt** [comment]
The test data I used for this test is the Ubuntu kernel source v4.7, fully built, as described here: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7/.  I tried smaller test data but didn't get the errors with them.

**Comment by markfasheh** [comment]
Adding some data, I can reproduce this on my end pretty easily just by running my duperemove 'smoke test' i'm working on getting the steps down further. Another interesting point is that btrfsck v4.5 does not show any corruption whereas v4.7 does, so it's worth looking into what changed there as well.

**Comment by markfasheh** [comment]
This btrfsprogs commit is the culprit:

https://github.com/kdave/btrfs-progs/commit/31d8235410985e0b64487354c9ba67d40c4bdfe3: btrfs-progs: check: supplement extent backref list with rbtree

I can reproduce on my end and confirm that backing btrfsprogs up to just before that commit no longer gives warnings.

**Comment by dcartt** [comment]
Can confirm at least part of this.  The problem does not occur with btrfs-progs v4.6.1.  The problem still occurs with btrfs-progs v4.7.1.

Are you going to report this?  I hope so because you appear to know what's going on.  I sure don't!

**Comment by markfasheh** [comment]
Yeah I was actually working on a fix myself. If I don't come up with anything viable soon, I'll post to the btrfs list. In any case, I'll keep this issue open until a fix is available.

Btw, this is what I have so far. It's not a complete fix however as I can still reproduce the errors.

https://github.com/markfasheh/btrfs-progs-patches/commit/0a9093c17e26430d4ba1da0d131fa23d95d81f1f

**Comment by markfasheh** [comment]
There's a kernel.org bugzilla open for this now, linking it here:

https://bugzilla.kernel.org/show_bug.cgi?id=155791

**Comment by markfasheh** [comment]
Ok so btrfs-progs v4.7.2 (just released) reverts both commits. Anyone having this problem can update to the latest btrfsprogs.

I'll close the duperemove end of this for now. Thanks again for the bug report!
