### ISSUE TITLE
RFE: move statistical information to the front of the line

### ISSUE THREAD

**Issue by leggewie** [markfasheh/duperemove#142]
When I run dupermove I get an output to the console like

    csum: /var/lib/lxc/trusty-i386.1/rootfs/var/log/bootstrap.log 	[267/269] (99.26%)
    csum: /var/lib/lxc/trusty-i386.1/rootfs/var/log/dpkg.log 	[268/269] (99.63%)
    csum: /var/lib/lxc/trusty-i386.1/rootfs/var/log/lastlog 	[269/269] (100.00%)

It would be better IMHO to move the numbers from the end of the line to the front or after the csum: stanza.  Reason is that this information is pretty static in length while the length of path and filename is very variable and that makes it harder than necessary to follow the information as it flies by.

**Comment by markfasheh** [comment]
Ok that all makes sense. Silly question, do we put the %complete at the very front like this:

(99.26%) [267/269] csum: /var/lib/lxc/trusty-i386.1/rootfs/var/log/bootstrap.log
(99.63%) [268/269] csum: /var/lib/lxc/trusty-i386.1/rootfs/var/log/dpkg.log
(100.00%) [269/269] csum: /var/lib/lxc/trusty-i386.1/rootfs/var/log/lastlog

or the other way around? And do we keep a tab between the completion information and the filename? (which is not shown in my example).

**Comment by markfasheh** [comment]
Ok I went ahead and picked, thanks for the suggestion.
