### ISSUE TITLE
xxhash is out of date and should be able to be linked dynamically

### ISSUE THREAD

**Issue by hogarthj** [markfasheh/duperemove#146]
The version of xxhash included is behind upstream by quite a margin and doesn't compile with the present upstream in place. the resultant compilation error is:

cc -Wall -ggdb -O2 -D_FILE_OFFSET_BITS=64 -DVERSTRING=\"v0.11.beta3\"  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -rdynamic -c csum-xxhash.c -o csum-xxhash.o  -lglib-2.0 -lsqlite3 -lm
csum-xxhash.c:46:16: error: field ‘td64’ has incomplete type
  XXH64_state_t td64;
                ^~~~
Present upstream is:

https://github.com/Cyan4973/xxHash/tree/master

It'd be good to get this back in line as it'll make packaging for distributions simpler, along with an option to the Makefile to link xxhash dynamically rather than include it directly.

**Comment by markfasheh** [comment]
Agreed, I'm not sure when I can get to this however I'd like to leave this issue open until we do.

**Comment by lorddoskias** [comment]
FWIW I have updated xxhash to the latest version from the upstream repo at https://github.com/Cyan4973/xxHash . I don't intend on making it dynamically linkable for the time being.
