### ISSUE TITLE
Document why someone would want to use each hash algorithm

### ISSUE THREAD

**Issue by ian-kelling** [markfasheh/duperemove#149]
And specify the default. For me and 99% of people reading the man page, the documentation is equivalent to

--hash=alg      alg can be foo or bar.

Googling does not help.

**Comment by markfasheh** [comment]
Thanks for reporting this - please check out this change from master branch 

72d428f4156eae84b57f0f1270bfcc55c4aebe79

and let me know if there's anything that you feel still needs explanation.

**Comment by ian-kelling** [comment]
Beautiful!
