### ISSUE TITLE
hang at end of dedupe

### ISSUE THREAD

**Issue by matthiaskrgr** [markfasheh/duperemove#154]
this was with https://github.com/markfasheh/duperemove/commit/7bb50b3a8ffd23c1e74a43c611286f9c6ce0d9cc

Have sufficiently large file of a normal user
Make non-cow copy as root (different permissions)
( cat file > file2 )
 dedupe the files as root
At the end of dedupe, duperemove will appear to hang.

backtrace (if I did this right) was  hash-tree.c:407

echo t > /proc/sysrq-trigger 
only got me 
[201324.588838] sysrq: SysRq : This sysrq operation is disabled.
in dmesg

**Comment by markfasheh** [comment]
Ahh ok that reproduces immediately for me, I probably messed up that patch. disregard this branch then until i get a chance to fix this up the right way.

**Comment by markfasheh** [comment]
So the hang from 
https://github.com/markfasheh/duperemove/commit/7bb50b3a8ffd23c1e74a43c611286f9c6ce0d9cc  shouldn't happen, you did mention that you got the hang at least once testing master branch? Do you still see that at all?

**Comment by markfasheh** [comment]
Oh btw I say 'shouldn't happen' because we replaced that patch with something that works  :)

**Comment by ivanbaldo** [comment]
@matthiaskrgr ping

**Comment by matthiaskrgr** [comment]
Looks fixed here, thanks.
