### ISSUE TITLE
duperemove on 2 identical 242G directories is taking over 6 days

### ISSUE THREAD

**Issue by ian-kelling** [markfasheh/duperemove#156]
top says duperemove is taking 100% cpu (1 core), and has been running for 8607 minutes (about 6 days of cpu time). I can't remember exactly when I started it, but it's been about a week.

`duperemove --dedupe-options=block --hashfile=dr-q-a-images -dhrA q-snap/a/images treetowl-btrbk/q.20160917T112834-0700/a/images`

There are 8 files which are vm images in the 2 directories to be deduped. They are on read-only snapshots. Unless there was a disk error, they are 100% identical. Here are the file sizes:

```
524288
727
262537728
98304
268173312
56999936
131165782016
128869007872
```

The end of the output looks like this:

```
[0xfbae80] Dedupe 6 extents (id: 5a21269f) with target: (2.1G, 128.0K), "/mnt/root/treetowl-btrbk/q.20160917T112834-0700/a/images/121G-image.qcow2"
[0xfb6400] Dedupe 119 extents (id: e47862ea) with target: (120.0G, 128.0K), "/mnt/root/treetowl-btrbk/q.20160917T112834-0700/a/images/121G-image.qcow2"
[0xfb64f0] (000068/392863) Try to dedupe extents with id 90dd2c9d
[0xfb6400] Dedupe 119 extents (id: e47862ea) with target: (120.0G, 128.0K), "/mnt/root/treetowl-btrbk/q.20160917T112834-0700/a/images/121G-image.qcow2"
[0xfb6450] Dedupe 119 extents (id: e47862ea) with target: (81.8G, 128.0K), "/mnt/root/q-snap/a/images/121G-image.qcow2"
[0xfb64f0] Dedupe 6 extents (id: 90dd2c9d) with target: (2.1G, 128.0K), "/mnt/root/q-snap/a/images/121G-image.qcow2"
[0xfbaf70] (000069/392863) Try to dedupe extents with id 86d64f43
[0xfb64a0] (000070/392863) Try to dedupe extents with id 7aa42a91
[0xfbaf70] Dedupe 11 extents (id: 86d64f43) with target: (17.4G, 128.0K), "/mnt/root/treetowl-btrbk/q.20160917T112834-0700/a/images/121G-image.qcow2"
```

The hashfile is 300 mb, I've copied it to a server assuming it might be useful to understand whats going on: https://iankelling.org/IbOvevFibnujokEu

version info:
* dupremove: commit d23b27cabff462c33d6b6832c65d3f363e2f21de, "Duperemove v0.11.beta4."
* btrfs-progs 4.7.3-1
* Linux  4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64

I can break into it with gdb and see what the stack trace looks like usually if needed.

**Comment by markfasheh** [comment]
Can you do a sysrq-t?   (`echo t > /proc/sysrq-trigger`) and give me the output of the duperemove processes (at least). If you see them in fiemap than it's probably btrfs going crazy over extent references.

**Comment by ian-kelling** [comment]
Not sure how to find the output of the relevant process, here is a tarball with 5 complete outputs over a minute or two:

https://iankelling.org/dupremove-kernel-tasks.tar.gz

Here are the relevant pids from pstree -p

```
          ├─sshd(2960)─┬─sshd(14914)───bash(14919)───duperemove(20662)─┬─{pool}(20763)
           │            │                                               ├─{pool}(20764)
           │            │                                               ├─{pool}(20765)
           │            │                                               ├─{pool}(20766)
           │            │                                               ├─{pool}(20767)
           │            │                                               ├─{pool}(20768)
           │            │                                               ├─{pool}(20769)
           │            │                                               └─{pool}(20770)
```

**Comment by markfasheh** [comment]
Ok go ahead and check out the stack if that's possible, thanks.

I didn't catch anything useful in the logs (lots of missed lines somehow) but also I'm not on my normal computer at the moment.

**Comment by ian-kelling** [comment]
seems the main proc is not handing gdb's signal, so I tried something else. So I looped over all the pids and got stacks from /proc/pid/stack, 20 times over 10 second intervals, dumped it into 20 files:

https://iankelling.org/duperemove-kernel-traces.tar.gz

It does look  like fiemap.

**Comment by ian-kelling** [comment]
Looking at htop, i see some of the threads jump from using cpu to not using cpu, but I found the total cpu time interesting:

```
20662 146h
20763 44:04.15
20764 124h
20765 59:04.16
20766 44:47.21
20767 8h51:42
20768 1h51:54
20769 56:09.49
20770 7h26:53
```

**Comment by markfasheh** [comment]
Interesting - are the processes killable right now?

Btw, you can try running with --dedupe-options=nofiemap and see if you still get that hang. Actually, I wonder if running show-shared-extents against those files would show a hang.

**Comment by ian-kelling** [comment]
I assume they will die if I send kill, or certainly with kill -9. I'm in no rush, so just let me know what you want me to do. It's still spitting out log lines every second or so, like the ones in the original report.

**Comment by ian-kelling** [comment]
Any other advice for me to debug this? Otherwise I will cancel it and rerun run with nofiemap. It's still running.

**Comment by markfasheh** [comment]
Yeah give it a go with nofiemap.

If that doesn't do it but we're not actually hanging then give --dedupe-options=noblock a shot - that will reduce the # of dedupe requests by calculating extents (how we used to do it if you recall). If neither helps then we'll need some more debugging.

Thanks

**Comment by markfasheh** [comment]
Oh lastly, if you just need this deduped and the directories are truly identical then fdupes mode should get you going again. That said, I really appreciate any help debugging the cause of your hang :)  :)

**Comment by ian-kelling** [comment]
So, I reran with nofiemap and it completed in less than a day, maybe a few hours. Thanks for the help.

**Comment by markfasheh** [comment]
Thanks for updating this Ian. I think this should have a FAQ entry in the man page so other users aren't quite as surprised. I'll try to work something up soon.
