### ISSUE TITLE
fdupes improvement

### ISSUE THREAD

**Issue by saintger** [markfasheh/duperemove#160]
Running the same command twice:

```
fdupes -r /foo | duperemove --fdupes
```

Gives exactly the same output result.

It would be nice if files which have been already deduplicated, can be ignored by duperemove (or not included in the output).

**Comment by markfasheh** [comment]
The only way we could remember which files were scanned is if we used a hashfile in fdupes mode. Functionally that's the same as issue #145 so I'm going to mark this as a duplicate. Feel free to watch that bug for updates. I'll update it with your use case.
