### ISSUE TITLE
fdupes mode skips small files

### ISSUE THREAD

**Issue by dougfultz** [markfasheh/duperemove#164]
I'm trying to use fdupes to help deduplicate lots of small files.  Since fdupes doesn't care about the file being smaller then the block size I'm using it to find duplicate files first.  Then passing the list to duperemove.  Unfortunately, duperemove still checks if the file size is less than the block size.

I haven't tested this yet, but my idea is to ignore blocksize restrictions setting it to 0 if the fdupes flag is used.

```
$ git diff
diff --git a/duperemove.c b/duperemove.c
index 0d5eb3c..15d5ddf 100644
--- a/duperemove.c
+++ b/duperemove.c
@@ -528,6 +528,7 @@ static int parse_options(int argc, char **argv, int *filelist_idx)
                                "list argument\n");
                        return 1;
                }
+               blocksize = 0;
                /* rest of fdupes mode is implemented in main() */
                return 0;
        }
```

**Comment by markfasheh** [comment]
There's a branch, issue#164 with a patch to implement this. I still need to think about how this interacts with inline data (which can't be deduped), and whether we care about that or not.

**Comment by Forza-tng** [comment]
I second this request. Small files that aren't inlined benefit from deduplication as it avoids extra underused 4KiB blocks on disk. Especially nice if the filesystem is mounted with a small max_inline value.

**Comment by JackSlateur** [comment]
Hello @Forza-tng 
All files are now processed, regardless of their size

Feel free to reopen this if you still have the issue
