### ISSUE TITLE
File modify timestamp is changed

### ISSUE THREAD

**Issue by greezybacon** [markfasheh/duperemove#165]
Technically, since the content of the file wasn't supposed to be affected by the deduplication process, the modify timestamp of the file should not change. Because it *is* changed by `duperemove`, file synchronization systems like `rsync` are severely impacted by the deduplication process.

It would be nice if the file's modify time were captured before dupes are removed, then after completion, the modify timestamp is restored.

**Comment by calestyo** [comment]
Anything new on this? Would be IMO quite a critical bug, as it would mean duperemove destroys user visible (meta)data.

I couldn't observe this behaviour however when run as root and -A

**Comment by markfasheh** [comment]
Hey, this was fixed a few kernel versions ago. If you give me time to look it up I'll let you know the exact versions. Also can you both tell me what kernels you're running?

**Comment by calestyo** [comment]
4.9.0

**Comment by calestyo** [comment]
Maybe you should add functionality, that duperemove requires a special switch to be run with unfixed versions.

**Comment by markfasheh** [comment]
Btw, just wanted to leave a note that this isn't forgotten, I've been rather busy lately and haven't had a chance to try reproducing.

**Comment by greezybacon** [comment]
@markfasheh I was able to get the code working to resolve the issue for me. I am able to run duperemove and then use rsync with a remote server, and there are no differences noted between the servers. Thanks for writing a great tool. I've opened #180 with my changes.

**Comment by markfasheh** [comment]
Closing this for now - Centos updated their kernels (see issue #180) and I have not been able to reproduce this on the 4.16 kernel I'm running now.
