### ISSUE TITLE
get duperemove into Debian

### ISSUE THREAD

**Issue by calestyo** [markfasheh/duperemove#166]
Hey.

Would be nice if upstream could perhaps put some effort into getting duperemove downstream into Debian :)

Cheers,
Chris.

**Comment by markfasheh** [comment]
I believe I had most of what was needed (some copyright headers IIRC) but if anyone wants to send patches I'd appreciate it.

**Comment by calestyo** [comment]
Actually there was some progress recently on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784856 and it's now waiting in the NEW queue (https://ftp-master.debian.org/new.html)...

So unless the ftp-masters find problems and reject it until these are resolved it should be in unstable soon.

But perhaps it makes sense to get in touch with the Debian maintainer (https://qa.debian.org/developer.php?login=peter.zahradnik@znik.sk) and merge code?

Cheers,
Chris.

**Comment by calestyo** [comment]
It's now in unstable.
