### ISSUE TITLE
master branch = current stable??

### ISSUE THREAD

**Issue by freswa** [markfasheh/duperemove#172]
The README states:
> The latest stable code (v0.11) can be found in master branch.

But there have been two commits recently. So I doubt that the master branch always contains the stable version, does it?

Are there any plans to release 0.11 as an archive or should I use the 0.11 branch/the master branch to distribute a stable version instead?

**Comment by markfasheh** [comment]
It's stable in that it passes all the same tests in the old code and some more. There are always bugs with any release.

I've been lax doing an official release but plan to get to that asap.

**Comment by freswa** [comment]
thx

**Comment by lpirl** [comment]
I was completely fine with the tags you added for the past releases, @markfasheh – maybe that is sufficient already.

**Comment by freswa** [comment]
Yes, tags work perfectly :)

**Comment by freswa** [comment]
@markfasheh Any progress here?

**Comment by markfasheh** [comment]
I'll make a final 0.11 tag soon, the commits in master look fine to me by the way so most likely I will just roll them right into the branch. I need to run some tests and give the issue tracker a reading first. Thanks all for your patience.

**Comment by lorddoskias** [comment]
0.11 and 0.11.1 have already been released so closing.
