### ISSUE TITLE
uninstall target in Makefile

### ISSUE THREAD

**Issue by jojoax** [markfasheh/duperemove#174]
How about to path in an "uninstall target" into the Makefile?
Here is a working patch for it.

root@pc6:/usr/src/duperemove# git diff
diff --git a/Makefile b/Makefile
index 0690bcf..a679523 100644

`--- a/Makefile
+++ b/Makefile
@@ -101,6 +101,14 @@ install: $(install_progs) $(MANPAGES)
                install -m 0644 $$man $(DESTDIR)$(MANDIR)/man8; \
        done
 
+uninstall:
+       for prog in $(install_progs); do \
+               rm -f $(DESTDIR)$(SBINDIR)/$$prog; \
+       done
+       for man in $(MANPAGES); do \
+               rm -f $(DESTDIR)$(MANDIR)/man8/$$man; \
+       done
+
 csum-test: $(csum_test_obj) csum-test.c
        $(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) $(csum_test_obj) -o csum-test csum-test.c  $(LIBRARY_FLAGS)

`

**Comment by markfasheh** [comment]
Thanks, we have an uninstall target now.
