### ISSUE TITLE
default output is too verbose

### ISSUE THREAD

**Issue by chrysn** [markfasheh/duperemove#175]
duperemove (as of 0.11) has an extremely verbose output by default, filling my complete 2k line backscroll deduplicating just two 1gb files. i wouldn't insist on following the [rule of silence](http://www.linfo.org/rule_of_silence.html) to the letter, but something proportional to the number of files (and not the number of extents) should imo be the upper bound for everything not `-v`erbose.

please consider changing the default verbosity, and maybe accept repeated `-v` arguments to obtain what is currently the verbose output.

**Comment by markfasheh** [comment]
Thanks for pointing this out. Your suggestion seems entirely reasonable, I'll put it on the list for our next revision.

**Comment by lubikx** [comment]
Hi, is this going to be implemented, please? There really should be some option to make the output less verbose.

Thanks.

**Comment by markfasheh** [comment]
To start, how about a 'quiet mode' which only prints errors, and the total dedupe results?

**Comment by lubikx** [comment]
Yeah, that will work. Thanks :)

**Comment by markfasheh** [comment]
Ok, I have an initial implementation in the 'quiet' branch (commit 48e1579) of duperemove.git. Any feedback would be much appreciated.

**Comment by daviessm** [comment]
The quiet branch works beautifully for me. I noticed that the `-q` option is missing from the `--help` text though.

**Comment by JackSlateur** [comment]
The quiet option as well as the man page has been merged, thank you for your suggestion
