### ISSUE TITLE
Provide option to cross filesystem boundaries

### ISSUE THREAD

**Issue by etskinner** [markfasheh/duperemove#178]
Man page shows:

> -x
> Don't cross filesystem boundaries, this is the default behavior since duperemove v0.11. The option is kept for backwards compatibility.

In btrfs, subvolumes act like different mount points (boundaries), but they could still benefit from de-duping. For example, consider a directory in a btrfs filesystem with subvolumes `1` and `2`, where there exist duplicate files `foo` in each:
```
.
├── 1
│   └── foo
│   └── bar
└── 2
    ├── foo
    └── baz
```

It would be useful to have an option that would allow for filesystem boundary crossing (something like `--nx` or `--subvolume`?). Ideally, duperemove would check if subvolumes that it recurses into are part of the same overall filesystem, and provide warnings if not.

**Comment by leggewie** [comment]
In the meantime I suppose what you want can be achieved by bind-mounting your subvolumes somewhere appropriate (/mnt or /tmp) and then run duperemove without -x on that mount.

**Comment by lorddoskias** [comment]
Current dedupe support in the kernel doesn't support dedupe across mountpoints so it makes no sense to support this in duperemove at present time.
