### ISSUE TITLE
Fedora 26, compile fail, /usr/bin/ld: cannot find /usr/lib64/libatomic.so.1.2.0

### ISSUE THREAD

**Issue by cmurf** [markfasheh/duperemove#182]
This is a bit odd, but I'm getting a build failure on Fedora 26.

cc  -Wall -ggdb -O2 -D_FILE_OFFSET_BITS=64 -DVERSTRING=\"v0.11.beta4\"  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -rdynamic   duperemove.o hash-tree.o results-tree.o rbtree.o dedupe.o filerec.o btrfs-util.o util.o memstats.o file_scan.o find_dupes.o run_dedupe.o csum.o dbfile.o interval_tree.o list_sort.o stats.o debug.o csum-xxhash.o xxhash.o csum-murmur3.o -o duperemove -Wl,--as-needed -latomic -lm  -lglib-2.0  -lsqlite3 
/usr/bin/ld: cannot find /usr/lib64/libatomic.so.1.2.0
collect2: error: ld returned 1 exit status
make: *** [Makefile:83: duperemove] Error 1

[chris@f26s duperemove]$ sudo find /usr/ -name libatomic*
/usr/lib/gcc/x86_64-redhat-linux/7/32/libatomic.a
/usr/lib/gcc/x86_64-redhat-linux/7/32/libatomic.so
/usr/lib/gcc/x86_64-redhat-linux/7/libatomic.so
/usr/lib64/libatomic_ops.so.1
/usr/lib64/libatomic_ops.so.1.0.3
/usr/lib64/libatomic_ops_gpl.so.1
/usr/lib64/libatomic_ops_gpl.so.1.0.3
/usr/share/licenses/libatomic_ops
/usr/share/doc/libatomic_ops

Digging around I found someone suggest removing -latomic, which I did from line 55 in Makefile, and now it compiles OK. I have compiled on this box previously, but I'm not certain if it was before or after the Fedora 25 -> 26 dnf upgrade (not a clean install so all previously available packages are still available, just new versions).

[chris@f26s duperemove]$ uname -r
4.11.9-300.fc26.x86_64
[chris@f26s duperemove]$ rpm -q gcc
gcc-7.1.1-3.fc26.x86_64

OK and after I 'dnf install libatomic' it installs libatomic-7.1.1-3.fc26.x86_64.rpm which installs /usr/lib64/libatomic.so.1.2.0 and now the original Makefile works OK.

**Comment by lorddoskias** [comment]
Duperemove now no longer links to libatomic explicitly. As it was unknown why this was needed in the first place I've removed the code.
