### ISSUE TITLE
libatomic not in dependencies

### ISSUE THREAD

**Issue by renich** [markfasheh/duperemove#186]
Hello,

I had to install libatomic as well. Not in the dependency list.

**Comment by lorddoskias** [comment]
Latest duperemove dynamic library list is: 

	linux-vdso.so.1 (0x00007fff873d5000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fb2b3e10000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fb2b3b07000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb2b3716000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb2b34a4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb2b3285000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb2b2ee7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb2b2ce3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb2b4345000)


I don't see libatomic there, so I consider this invalid.

**Comment by renich** [comment]
fair enough. Looked into the other binaries and didn't find it. I, honestly, don't remember what issue I ran into; which got solved by installing libatomic. I'll get back to you on that one.

**Comment by lorddoskias** [comment]
No need, turns out indeed duperemove was being linked against libatomic but since the __atomic functions are being provided by gcc that's unneeded. I have now removed that in 06160235310a98f41c3f0e46e8f42e57dba11bc3
