### ISSUE TITLE
could not compile duperemove on debian 8 jessie

### ISSUE THREAD

**Issue by mhochhaus** [markfasheh/duperemove#188]
Hi,

i've tried to compile duperemoveom my NAS Box, but i didn't work.

Here is the output:

/duperemove# make
Package sqlite3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sqlite3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sqlite3' found
Package sqlite3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sqlite3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sqlite3' found
Package sqlite3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sqlite3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sqlite3' found
Package sqlite3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sqlite3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sqlite3' found
cc  -Wall -ggdb -O2 -D_FILE_OFFSET_BITS=64 -DVERSTRING=\"v0.11.beta4\"  -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include   -rdynamic   -c duperemove.c -o duperemove.o -Wl,--as-needed -latomic -lm  -lglib-2.0  
In file included from duperemove.c:41:0:
dbfile.h:4:21: fatal error: sqlite3.h: Datei oder Verzeichnis nicht gefunden
 #include <sqlite3.h>
                     ^
compilation terminated.
Makefile:73: recipe for target 'duperemove.o' failed
make: *** [duperemove.o] Error 1

apt list --installed shows
sqlite3/oldstable,now 3.8.7.1-1+deb8u2 i386  [installiert]
 as installed, so what other dependencies are needed?

**Comment by Nable80** [comment]
Hi,
in most distros (including Debian) one has to install development packages to build anything. So you should install libsqlite3-dev (please, note the **-dev** suffix), not just the run-time library.

**Comment by goldwynr** [comment]
Closing based on Nable80's comment.
