### ISSUE TITLE
A couple of problems with duperemove

### ISSUE THREAD

**Issue by ghost** [markfasheh/duperemove#190]
I'm using `=sys-fs/duperemove-0.11_beta4` on a Gentoo Linux desktop system.

I have a single btrfs root filesystem with multiple subvolumes inside. Every day I manually take a snapshot of each single subvolume for backup purposes. For example I have a `@bitcoin` subvolume mounted at `/home/fturco/.bitcoin`. Snapshots for this subvolume are stored in the`/home/fturco/.bitcoin/.snapshots` directory.

I'm running `duperemove` as follows:

    nice -n 19 ionice -c 3 duperemove -rdh --hashfile=/root/duperemove.hash /

This is taking a lot of time (days) and it is slowing down my system a lot. I noticed `duperemove` also scans snapshots, but is this needed? Aren't btrfs snapshots already deduplicated when they are made? If so, is there an option for excluding them?

My other problem is that my system cannot be comfortably used while `duperemove` is running due delays when performing certain I/O operations, for example saving a document to disk. As you can see I'm using both `nice` and `ionice` in order keep the system responsive, but that's not helping much. Is there some other thing I can try?

Thanks.

**Comment by Floyddotnet** [comment]
2017-10-13 14:55 GMT+02:00 Francesco Turco <notifications@github.com>:

> I'm using =sys-fs/duperemove-0.11_beta4 on a Gentoo Linux desktop system.
>
> I have a single btrfs root filesystem with multiple subvolumes inside.
> Every day I manually take a snapshot of each single subvolume for backup
> purposes. For example I have a @bitcoin subvolume mounted at
> /home/fturco/.bitcoin. Snapshots for this subvolume are stored in the
> /home/fturco/.bitcoin/.snapshots directory.
>
> I'm running duperemove as follows:
>
> nice -n 19 ionice -c 3 duperemove -rdh --hashfile=/root/duperemove.hash /
>
> This is taking a lot of time (days) and it is slowing down my system a
> lot. I noticed duperemove also scans snapshots, but is this needed?
> Aren't btrfs snapshots already deduplicated when they are made? If so, is
> there an option for excluding them?
>
btrfs snapshots are only a copy of the metadata (the extend tree) at the
time there are create. if the original data change the snapshot wont be
effect because new data would written in a new extend. so no deduplication
is needed.

but duperemove breaks this by design because its build a new extend tree
and after this there are no more shared areas / extends in the files.
snapshots can't be updated with the new extend tree because thay are
readonly by design.

The deupe-IOC in the btrfs implementation hase big problems with lage files
because its build every time a complete new extend-tree and write them
instend of merge a list into one new extend-tree. this isn't a problem of
duperemove itself.

> My other problem is that my system cannot be comfortably used while
> duperemove is running due delays when performing certain I/O operations,
> for example saving a document to disk. As you can see I'm using both nice
> and ionice in order keep the system responsive, but that's not helping
> much. Is there some other thing I can try?
>
> Possible use another sheduler could help a litlle. but realy only a little.
>

**Comment by fturco** [comment]
Unfortunately I tried both the CFQ and the Deadline I/O schedulers without any significant performance improvement.

**Comment by Floyddotnet** [comment]
2017-10-13 21:31 GMT+02:00 Francesco Turco <notifications@github.com>:

> Unfortunately I tried both the CFQ and the Deadline I/O schedulers without
> any significant performance improvement.
>
As expected, because the root of the problem is in the kernel.

**Comment by goldwynr** [comment]
For better response time for other interactive jobs, Having you tried reducing the number of threads for duperemove using --io-threads and --cpu-threads options?

**Comment by goldwynr** [comment]
On 10/13/2017 01:35 PM, Peter Becker wrote:
> 2017-10-13 14:55 GMT+02:00 Francesco Turco <notifications@github.com>:
> 
>> I'm using =sys-fs/duperemove-0.11_beta4 on a Gentoo Linux desktop system.
>>
>> I have a single btrfs root filesystem with multiple subvolumes inside.
>> Every day I manually take a snapshot of each single subvolume for backup
>> purposes. For example I have a @bitcoin subvolume mounted at
>> /home/fturco/.bitcoin. Snapshots for this subvolume are stored in the
>> /home/fturco/.bitcoin/.snapshots directory.
>>
>> I'm running duperemove as follows:
>>
>> nice -n 19 ionice -c 3 duperemove -rdh --hashfile=/root/duperemove.hash /
>>
>> This is taking a lot of time (days) and it is slowing down my system a
>> lot. I noticed duperemove also scans snapshots, but is this needed?
>> Aren't btrfs snapshots already deduplicated when they are made? If so, is
>> there an option for excluding them?
>>
> btrfs snapshots are only a copy of the metadata (the extend tree) at the
> time there are create. if the original data change the snapshot wont be
> effect because new data would written in a new extend. so no deduplication
> is needed.
> 
> but duperemove breaks this by design because its build a new extend tree
> and after this there are no more shared areas / extends in the files.
> snapshots can't be updated with the new extend tree because thay are
> readonly by design.

No, the duperemove does not build a new extent tree. It merely performs
a BTRFS_IOC_FILE_EXTENT_SAME on the extents/blocks which are same
(depending on the dedupe-options you provide).

> 
> The deupe-IOC in the btrfs implementation hase big problems with lage files
> because its build every time a complete new extend-tree and write them
> instend of merge a list into one new extend-tree. this isn't a problem of
> duperemove itself.

Do you have a testcase to demonstrate this?


-- 
Goldwyn

**Comment by fturco** [comment]
> For better response time for other interactive jobs, Having you tried reducing the number of threads for duperemove using --io-threads and --cpu-threads options?

@goldwynr: `--cpu-threads=1` and `--io-threads=1` seem to help somewhat. Thanks for the suggestion.

**Comment by JackSlateur** [comment]
Hello,

Many improvements have been made since that issue was opened
Please check the last code from master and reopen this issue if you still have an issue
