### ISSUE TITLE
Create 0.11 release

### ISSUE THREAD

**Issue by fryfrog** [markfasheh/duperemove#193]
If 0.11 is ready for a release, it'd be great if it could get one.

For https://aur.archlinux.org/packages/duperemove/ :)

**Comment by markfasheh** [comment]
I like to think that I left 0.11 a pretty good state - it was at least the first one that I ran a 'test suite' against but the truth is that I haven't had time for personal projects in a while now. I need to go through the bugs, and address some pull requests. In the meantime I would tread v0.11.beta4 as being extremely close to what the final release would be.

**Comment by fryfrog** [comment]
Awesome, that sounds like the right thing to do. I'm sure you'll do a 0.11 release when it is time, closing issue. :)
