### ISSUE TITLE
Only csum delta since last run: btrfs subvolume find-new

### ISSUE THREAD

**Issue by HaleTom** [markfasheh/duperemove#194]
To drastically improve the csum run time, could duperemove use `btrfs subvolume find-new` to only checksum files changed since the last run?

[`bedup`](https://github.com/g2p/bedup) supports incremental deduping, (but currently [doesn't support deduping RO snapshots](https://github.com/g2p/bedup/issues/93))

Alternatively, could it be possible to READ csums from a previously created file?

**Comment by markfasheh** [comment]
Hi, this is implemented in the v0.11 release of duperemove.
