### ISSUE TITLE
FAQ: Can duperemove be resumed

### ISSUE THREAD

**Issue by leggewie** [markfasheh/duperemove#198]
Hello,

thank you for an awesome tool.  I am currently running it on a 100GB SSD partition and even with -b 1024k it takes around 3 days to finish.  This left me wondering if I can resume duperemove after an interruption or if it will restart from scratch?  I think this would be a great addition to answer in the FAQ section of duperemove/duperemove.8

**Comment by markfasheh** [comment]
Hi, yes Duperemove v0.11 is resumable, if you're using a hashfile. If I remember correctly, the dedupe stage might redo work but the scan stage will definitely skip files it's already seen.

What version of duperemove are you using and what step is taking the longest?
