### ISSUE TITLE
ERROR: hash-tree.c:289

### ISSUE THREAD

**Issue by dolorosus** [markfasheh/duperemove#200]
Sometimes I got this error commit b83841c  :

Adding files from database for hashing.
Loading only duplicated hashes from hashfile.
ERROR: hash-tree.c:289
[stack trace follows]
[0x40bd17]
[0x40847e]
[0x411424]
[0x406fc9]
[0x4d47dc]
[0x407a27]
Aborted

Tried to build with DEBUG=1, but executing this build leads to 
error while loading shared libraries: libasan.so.4: cannot open shared object file: No such file or directory

What can I do do to provide more details?

**Comment by markfasheh** [comment]
Hi, are you using a hashfile? 

If so, could you load it up in sqlite and run this sql (sorry if it's ugly and rudimentary):

`
select files.filename, files.ino, files.subvol, files.size from files join (select hashes.ino, hashes.subvol from hashes where hashes.flags & 0x8) AS partials where files.ino = partials.ino AND files.subvol = partials.subvol;
`

You can edit the filename(s) if you like. Then just get me some basic information on the files as they are on disk:

`stat filename`
`filefrag -e filename`

Thanks!

**Comment by dolorosus** [comment]
Hi,

yes I'm using a hashfile, here's the result of the given sql command and the output of stat for each file.
[hashfile-broken.zip](https://github.com/markfasheh/duperemove/files/2035838/hashfile-broken.zip)

Unfortunally filefrag is missing on my nasbox. So I can't provide it's output

Best wishes
Dolorosus

**Comment by JackSlateur** [comment]
Hello,

Many improvements have been made since that issue was open, including strict data validation for the hashfile

I'll close this issue, please check the code from master and reopen it if you still face the issue

Best regards,
