### ISSUE TITLE
duperemove and cp --reflink=always file

### ISSUE THREAD

**Issue by minecraft2048** [markfasheh/duperemove#205]
Does duperemove skips files that are `cp --reflink=always` copied? I think that it should, but it doesn't finish the operation immediately

How I tested it:
```
mkdir testfile
cd testfile
fallocate -l 5G test.img
cp --reflink=always test.img test1.imt
duperemove --lookup-extents=yes -d  .
```

I expect this to start and then it recognizes that they are both the same file sharing the same reflink thing and it skips those file, but then duperemove uses one of my cpu and it takes 5-10 minutes to finish it to only result with 0 extents being changed

**Comment by markfasheh** [comment]
Hi, can you try with ```--dedupe-options=noblock``` ?

**Comment by reedriley** [comment]
+1, this is happening for me as well.  It also happens with files I've previously deduplicated using `duperemove` if I remove the hashfile.

More specifically, I'm running BTRFS (kernel: 4.14.65-gentoo, userspace: v4.16.1) on my NAS.  I'm using v0.11, and running it as root.  Here's the specific command line I've reproduced this with:
```
/usr/sbin/duperemove --hashfile=/root/storage.hash -b 1M --skip-zeroes --dedupe-options=noblock -A -dhr --io-threads=2 --cpu-threads=2 /storage
```

**Comment by reedriley** [comment]
Ah, nm - I may have answered my own questions here....  I'm not passing `--lookup-extents=yes`.  If that's it, please disregard!

**Comment by JackSlateur** [comment]
Hello,

Extents that are already-shared are always hashed : without this, we would not be able to deduplicate a new, unshared-file which may store the same data

While the existing hashes could be copied instead of being recomputed, I believe the complexity is not worth it
Your test script is now quite fast:
```
$ fallocate -l 5G test.img
$ cp --reflink=always test.img test1.imt
$ /usr/bin/time -v duperemove -drh . --dedupe-options=partial |& grep -e Elapsed -e "Maximum resident set size"
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:07.38
	Maximum resident set size (kbytes): 21472
```

If I test with actual data:
```
$ dd if=/dev/urandom bs=1G count=5 of=test.img
$ cp --reflink=always test.img test1.imt
$ /usr/bin/time -v duperemove -drh . --dedupe-options=partial |& grep -e Elapsed -e "Maximum resident set size"
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:27.81
	Maximum resident set size (kbytes): 33476
```

Indeed, the time spent on the dedupe phase could be improved (in that last test, it took 4 sec to hash the 10GB, and 21sec to deduplicate the already-shared extents)
