### ISSUE TITLE
manpage does not inform about: if block is enabled, no printing

### ISSUE THREAD

**Issue by alexander-n8hgeg5e** [markfasheh/duperemove#210]
if (run_dedupe) {
....
	} else {
                   if (block_dedupe)
		                if (block_dedupe)
			                  debug_print_hash_tree(&dups_tree);
		                else
			                   print_dupes_table(&res);

**Comment by lorddoskias** [comment]
Can you elaborate on what is the issue you are experiencing?

**Comment by alexander-n8hgeg5e** [comment]
The program does only debug_print_hash_tree not print_dupes_table if block_dedupe. This is not described in the manpage. (at that time i looked at it). I did not expect to change the printing behaviour by selecting "block-mode".

**Comment by lorddoskias** [comment]
Turns out debug_print_hash_tree has been disabled for about 2 years by commit 2a61725cce5a . And in fact block_dedupe is also removed so I'd consider this an invalid report, based on an old version.
