### ISSUE TITLE
Hashfile extends the scope of commandline arguments

### ISSUE THREAD

**Issue by stoecker** [markfasheh/duperemove#217]
When you use a hashfile for storing data more than once, then duperemove checks dupes which it shouldn't.

E.g. you call duperemove first with files a, b and c and abort after the hashing phase.

Then later you call duperemove with files d, e, then after the hashing phase it will also search for dupes e.g. between file a and b instead of only processing d and e.

It seems it processes all entries in the hash file and not only the ones relevant for current run.

duperemove version 0.11.1

**Comment by lorddoskias** [comment]
Can you provide the exact command line you are running ?

**Comment by stoecker** [comment]
Sorry. I don't use that tool anymore at all.
