### ISSUE TITLE
Add FAQ "I got two identical files, why are they not deduped"

### ISSUE THREAD

**Issue by axkibe** [markfasheh/duperemove#218]
Answer: Because they are fragmented differently. On XFS you can try running "xfs_fsr" to defragment them before and thus the extents become duplicates. For BTRFS I don't know.

**Comment by Ferroin** [comment]
Equivalent on BTRFS would be running `btrfs filesystem defrag` on each of the individual files.

**Comment by HaleTom** [comment]
It would be great if this could be done within `duperemove` (perhaps if enabled by an option).

Am I right in thinking that there's no way of defraging files which have a dupe in a btrfs RO snapshot?

**Comment by KyleSanderson** [comment]
Indeed, this would be incredibly useful.

**Comment by lorddoskias** [comment]
I've added this to the FAQ in pull req #235 . Is it clear enough ?

**Comment by brunoais** [comment]
@lorddoskias I'd add that it is out of duperemove's control

**Comment by lorddoskias** [comment]
> @lorddoskias I'd add that it is out of duperemove's control

The thing is it's not entirely outside of duperemove control. I.e that's the way the current implementation works so it could be re-engineered to work with some other way which would handle this case. I guess I should state that this *might* change sometimes in the future.

**Comment by brunoais** [comment]
That works too, IMO.

**Comment by lorddoskias** [comment]
FAQ entry has been added.
