### ISSUE TITLE
duperemove follows moved file through symlinks to other filesystem

### ISSUE THREAD

**Issue by maweki** [markfasheh/duperemove#230]
So i have the following directory structure

```
ls -alh /home/maweki/.local/share/
lrwxrwxrwx. 1 maweki maweki   31 27. Mai 13:08  gnome-boxes -> /home/maweki/.fast/gnome-boxes/
```
and the following mounts:

```
/dev/sde on /home type btrfs (rw,noatime,seclabel,space_cache,subvolid=5,subvol=/)
/dev/sdf on /home/maweki/.fast type ext4 (rw,relatime,seclabel)
```

I duperemove with the following command: `/usr/sbin/duperemove -dhr --hashfile=/home/.duphash --io-threads=1 /home` which worked before I created the symlink and moved the contents of the directory. After moving I get this:

```
[root@maweki-desktop ~]# /usr/sbin/duperemove -dhr --hashfile=/home/.duphash --io-threads=1 /home
Gathering file list...
Adding files from database for hashing.
"/home/maweki/.local/share/gnome-boxes/images/fedora-unkno": Can only dedupe files on btrfs or xfs (experimental)
```
Duperemove looks up the file from its hash directory and follows the symlink onto another filesystem. I am not sure whether duperemove should follow symlinks at all but in this case after following the symlink it should check whether it had crossed filesystems or not. duperemove shouldn't follow the symlink if it crosses the filesystem. I use version "0.11.1" where `-x` is said to be the default.

**Comment by lorddoskias** [comment]
Closing as this has been fixed in trunk, if you find any other issues open a new issue.
