### ISSUE TITLE
util.c assumes SMT ratio

### ISSUE THREAD

**Issue by Jannik2099** [markfasheh/duperemove#243]
In [util.c](https://github.com/markfasheh/duperemove/blob/3985c776f2e1eb654e4d1962bfcdff08468ddff9/util.c#L231) , get_core_count assumes SMT to have a ratio of 2 threads per 1 core.
However there are lots of CPUs with different ratios outside of x86: POWER has 4 and 8, arm64 has 2 and 4, SPARC has 8, just to name a few.

Perhaps take a look at how lscpu from util-linux solves this - afraid my pity C skills won't be of help here

**Comment by lorddoskias** [comment]
If you have access to such a machine care to show me the output of your `/sys/devices/system/cpu/cpu0/topology/thread_siblings_list` file.
