### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mgorny** [markfasheh/duperemove#254]
The 0.11.1 release fails to build with gcc-10. Could you consider cutting a new release?

**Comment by lorddoskias** [comment]
Sure I guess there have been enough fixes to warrant another minor release. Just out of curiosity can't you simply use master?

**Comment by lorddoskias** [comment]
I've release https://github.com/markfasheh/duperemove/releases/tag/v0.11.2

**Comment by mgorny** [comment]
I could make a snapshot off master but having a release is better for everyone.
