### ISSUE TITLE
Enhancement: Use sqlite3 WAL mode for hash.db

### ISSUE THREAD

**Issue by Forza-tng** [markfasheh/duperemove#264]
sqlite has a WAL mode that has a much better performance for btrfs filesystems. It would be good if duperemove would change to use WAL mode. It should lead to a much less fragmented sqlite database, which I guess is the biggest benefit for duperemove.

It is already possible to use WAL-mode with duperemove by doing the following.

* Run duperemove briefely to create the hash-file. 
* Open the hashfile: `sqlite3 hash.db`
* Set WAL-mode `PRAGMA journal_mode=wal;`
* close  sqlite3.
* Run duperemove again.

Reference to performance impact on Btrfs: https://wiki.tnonline.net/w/Blog/SQLite_Performance_on_Btrfs

**Comment by JackSlateur** [comment]
Hello @Forza-tng 
WAL-mode is now used in the latest release

Thank you for your report
