### ISSUE TITLE
Duperemove v0.11.3 says it is v0.12.dev

### ISSUE THREAD

**Issue by hunleyd** [markfasheh/duperemove#270]
Just downloaded the tar.gz from the 0.11.3 release, compiled, and installed:
```
[I] ➜ duperemove --help
duperemove v0.12.dev
Find duplicate extents and optionally dedupe them.

Basic usage: duperemove [-r] [-d] [-h] [-v] [-A] [--hashfile=hashfile] OBJECTS
```

Is it really from the .12 dev?

**Comment by lorddoskias** [comment]
Doh, it was released from HEAD branch but I do have a commit which changed the ver in the makefile. I guess I will have to re-spin it...
