### ISSUE TITLE
Outdated usage info

### ISSUE THREAD

**Issue by TheSeven** [markfasheh/duperemove#272]
This does no longer appear to be accurate:
https://github.com/markfasheh/duperemove/blob/96dc4dab5b238d8238b19cfdd1b12d2223fe4756/duperemove.c#L296

**Comment by lorddoskias** [comment]
Well, technically `[no]block` is still accepted, but is ignored. But I agree it can be removed.

**Comment by lorddoskias** [comment]
Fixed in c1c1cb2d7e97769c0453f16619e57314bf3a67ff

**Comment by TheSeven** [comment]
Well now it's just missing same/fiemap/partial, that line wasn't the only thing wrong with that message ;)
