### ISSUE TITLE
Documentation: please describe prerequisites and how to get there

### ISSUE THREAD

**Issue by supersexy** [markfasheh/duperemove#274]
I ran into the `Dedupe for file had status (-95) "Operation not supported"` error because I was not able to understand the prerequisites needed to successfully use this software. I had an xfs file system and no clue if it was formatted with the needed options or not and how to check that. 

Also it is quite hard to find relevant information re "extents" and "kernel ioctl" to understand what is going on behind the scenes if one can not take the time to study kernel hacking in depth but instead just wants to quickly dedupe a disk. 

So I would like to ask to add some information about how to prepare media with the right file system options for all supported file systems with examples and add a few sentences about how that deduplication works. 

Thank you very much!

**Comment by lorddoskias** [comment]
Probably I can include a section in the FAQ, so far it seems 2 people (you and seafood in an earlier issue where you also commented) have come accross this so I'm not 100% sure this really warrants a rather detailed documentation. Also a simple search for `xfs reflink support` does yield 2 relevant results: 

https://blogs.oracle.com/linux/post/xfs-data-block-sharing-reflink
https://strugglers.net/~andy/blog/2017/01/10/xfs-reflinks-and-deduplication/

**Comment by JackSlateur** [comment]
Hello @supersexy 

The 
wiki has been updated
