### ISSUE TITLE
optimization of extents already shared?

### ISSUE THREAD

**Issue by brainchild0** [markfasheh/duperemove#290]
I have noticed through casual use that if files in the input set already share extents, then each file is still processed separately  for checksum computation. Is it possible to avoid computation of checksums for extents previously determined in the same operation, because they were referenced by files earlier processed?

I am using version 0.11.2 under Linux Mint 21 with kernel 6.0.0.

**Comment by JackSlateur** [comment]
Hello,

Unchanged files are no longer checksumed nor deduplicated, unless some extents have to be shared with a new file
Could you check the latest code ?
