### ISSUE TITLE
Warn if no files are checked

### ISSUE THREAD

**Issue by dingens** [markfasheh/duperemove#294]
When you just run `duperemove` it won't run normally, but display the usage notes instead.

However, when you run `duperemove -h` or `-r`, it seems to run normally, but actually checks nothing at all (because no files/directories are given). The output is very misleading then:
```
$ duperemove -h
Gathering file list...
No dedupe candidates found.
```

I suggest to either
- assume `.` as argument if no directories are listed (as does `ls` for example), or
- when duperemove is called in such a nonsensical way, warn the user. Or just present the usage dialog, like when it is run without any arguments.

**Comment by JackSlateur** [comment]
Thank you @dingens for the report!
