### ISSUE TITLE
Support for ZFS deduplication

### ISSUE THREAD

**Issue by ninewan** [markfasheh/duperemove#300]
I would like to know if there are any plans to support ZFS deduplication. 
Considering that ZFS introduced block cloning support in version 2.2.0, I believe incorporating ZFS deduplication functionality into it would be very meaningful.

https://github.com/openzfs/zfs/releases
[zfs-2.2.0-rc3](https://github.com/openzfs/zfs/releases/tag/zfs-2.2.0-rc3)
[zfs-2.2.0-rc2](https://github.com/openzfs/zfs/releases/tag/zfs-2.2.0-rc2)

**Comment by markfasheh** [comment]
Based on [this page](https://github.com/openzfs/zfs/pull/15050) it doesn't look like ZFS dedupe_file_range does anything other than return EOPNOTSUPP or ENOTTY. Unfortunately we wouldn't be able to support dedupe on ZFS until it supports those calls.
