### ISSUE TITLE
Incorrect implementation of `is_block_zeroed`

### ISSUE THREAD

**Issue by amonakov** [markfasheh/duperemove#317]
The new implementation of `is_block_zeroed` at https://github.com/markfasheh/duperemove/blob/ed75acd1e09585779991763d1400e03a0d57fe3c/file_scan.c#L570-L574 is incorrect, it checks if all bytes in the block are the same, but not if they are all zero (broken by a [recent commit](https://github.com/markfasheh/duperemove/commit/3a5f00d74f3c7dd60409a3a238d3f57a0160652a)).

**Comment by JackSlateur** [comment]
That's a shame
Thank you for your report (fixed by 2a235bf17fbca7bc332b3acc35043c75a22548e3)
