### ISSUE TITLE
Please don't change existing releases -- make new ones instead

### ISSUE THREAD

**Issue by bjornfor** [markfasheh/duperemove#330]
Hi, I'm a user/maintainer of https://github.com/nixos/nixpkgs and think something unfortunate happened with the 0.14 release:

* I think we observed that dupremove changed the contents of 0.14 after the release, see https://github.com/NixOS/nixpkgs/pull/268388#issuecomment-1820007438
* After updating from old 0.14 to new 0.14, there were build regressions that had to be fixed with https://github.com/NixOS/nixpkgs/pull/268837/commits/c9da1f6842cfcad04d7e0ab2a314b263efe4fb46

Thanks for considering this input from a downstream!

**Comment by JackSlateur** [comment]
Hello,

Sorry for the inconvenience, that will not happen again
