### ISSUE TITLE
Quiet flag doesn't suppress exclude pattern printing

### ISSUE THREAD

**Issue by hhyyrylainen** [markfasheh/duperemove#334]
Running duperemove 0.13 with the `-q` flag, I still get the following output:

```
Adding exclude pattern: /home/.snapshots/*
```

For cron usage it would be nice if the quiet option also prevented the exclude patterns from being printed. Sorry if this is already fixed in 0.14.1 (I'm using the version from Fedora repository).

**Comment by JackSlateur** [comment]
Hello @hhyyrylainen 
This issue was fixed in master by ed80c8b19ba6f654d04f9f1a2a67d2faf633cfcc, which is not yet part of a release

Thank you for your report!
