### ISSUE TITLE
Allow exclusion of files by an extension

### ISSUE THREAD

**Issue by ppetr** [markfasheh/duperemove#338]
Currently `--exclude=*.foo` doesn't seem to work. It would be quite useful for example for files whose content is being created and yet unfinished.

Also please document how to use this in the _man_ page.

**Comment by JackSlateur** [comment]
Hello @ppetr 
I believe this issue is now fixed

Please note that you should probably use quotes around the pattern: `--exclude="*.foo"`

The behavior is documented in the man page (check for "exclude")

Best regards,

**Comment by daire-byrne** [comment]
But does this work recursively?

Like if I want to exclude all xml files anywhere in the tree?

**Comment by JackSlateur** [comment]
Yes it does

For instance, when I do `duperemove --hashfile=/tmp/hashes --exclude "*.mp3" -r .`, then the following file is excluded: `./music/something.mp3`

This also works: `duperemove --hashfile=/tmp/hashes --exclude "*/music/*" -r .`
