### ISSUE TITLE
`--exclude=` doesn't work

### ISSUE THREAD

**Issue by mooreye** [markfasheh/duperemove#343]
I want to exclude a location:
```
sudo duperemove -drh --hashfile=/opt/dedupe.hash --exclude=/home/user/Foo/ /home/user/
```
The output says:
```
Adding exclude pattern: /home/user/Foo/
```
but then it still dedups it:
```
[0x55a36b429d30] Dedupe 1 extents (id: 7e1c978a) with target: (6.8GB, 128.0KB), "/home/user/Foo/file"
```

I also tried `--exclude=/home/user/Foo/\*` and `--exclude=/home/user/Foo/file` but none work.

Version: `0.14.1`
Using Fedora 40

**Comment by JackSlateur** [comment]
Hello @mooreye 
The `--exclude` option takes a regex : in your case, you should use something like that:
```
sudo duperemove -drh --hashfile=/opt/dedupe.hash --exclude="/home/user/Foo/*" /home/user/
```

**Comment by drindt** [comment]
@JackSlateur unfortunately no. The version `0.14.1` provided by Fedora hast this issue too. Relative or absolute, makes no difference.

**Comment by JackSlateur** [comment]
Hello,
I've no longer the required time to work on duperemove
As far as I know, the feature is working on master, a new release has been published from that
Hope that will fix your issue

Best regards
