### ISSUE TITLE
BTRFS hash reuse

### ISSUE THREAD

**Issue by http403** [markfasheh/duperemove#354]
I'm using BTRFS with xxhash. Since hash is already calculated once, can `duperemove` use them directly, rather calculating again? This can also eliminate the need of a hash file.

Thanks

**Comment by JackSlateur** [comment]
Hello @http403 
As far as I know, there are no way to get an extent's hash via ioctl(2) or else
Others have managed to do that by reading the block storage directly and fetching the hash behind the kernel's back, this will not be implemented

Until Linux exposes the checksums, this feature cannot be implemented

Best regards,

**Comment by dmromanov** [comment]
There is now an ioctl to get raw checksums, starting from Kernel 7.2

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c6153ed23ed6a2bb8a5891382c06134674610f86
