### ISSUE TITLE
Does this work for unmounted loopback devices?

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [markfasheh/duperemove#356]
Does this work for unmounted loopback devices? I have a bunch of unmounted and some partially broken loopback devices that i plan on fixing at one point but id like alot of storage on my hard drive for some of the stuff id like to do.

**Comment by JackSlateur** [comment]
Hello @SpiderUnderUrBed 
Your lookback devices are nothing but files (which happens to contains a filesystem, but that is of no concern)
As such, they can be deduplicated, depending on:
- their content (are parts of them duplicated etc). Block-based lookup would be necesseray to yield some results : `--dedupe-options=partial`
- the underlying filesystem that stores the images: only btrfs and xfs are supported at this time, I'm waiting for bcachefs to reach upstream and have yet to check out the last improvements in zfs

Best regards,
