### ISSUE TITLE
Problem with x86_32 compilation.

### ISSUE THREAD

**Issue by iiv3** [markfasheh/duperemove#36]
>file_scan.o: In function `csum_whole_file':
>/tmp/duperemove/file_scan.c:227: undefined reference to `__sync_add_and_fetch_8'

The missing function is gcc intrinsic and as such is not defined in any header file, nor does it require separate library.
It however needs explicitly specified architecture that actually supports the atomic operation. For me -march=i586 did the trick (i486 failed).

Since all 64 bit architectures are newer than than i586, the intrinsic is already supported.

On a side note, my build script does provide CFLAGS with my native architecture, but the makefile overrides it.

**Comment by markfasheh** [comment]
custom CFLAGS should be working with the makefile these days, let me know if it doesn't for you.
