### ISSUE TITLE
Question: What is considered to be a "small" dataset?

### ISSUE THREAD

**Issue by jedenastka** [markfasheh/duperemove#362]
I was considering deduplication for a possibly highly redundant (on a block level, not necessarily on a file level) dataset. Seems like duperemove is the most complete solution for this, so I was reading the docs.

I encountered this statement in the Examples section:

> You only want to use this for small data sets [...]

How large is a "small" dataset considered to be? Mine is around 300 GiB (not deduplicated) and expected to grow to possibly a few terabytes.

Would splitting it and having separate runs with separate hashfiles help the program, if there are subsets that are less likely to be duplicated between each other?

**Comment by JackSlateur** [comment]
Hello @jedenastka 

300GB is a small dataset: you can run `duperemove -dr /foo`, wait an acceptable amount of time and call it a day
However, with such command, for each run, the whole dataset will be read, all data will be computed

The recommended way is to use a hashfile: `duperemove --hashfile=/my-hashfile -dr /foo` : in this mode, the next run will only read new/modified files, and only work on them

Hashfile brings no drawback, except the need to store a relatively small file somewhere (mine: 216MB for a 146GB dataset)
Internally, most of the code is the same: it uses a sqlite database. If you do not use hashfile, then the sqlite is stored in memory.

Best regards,

**Comment by jedenastka** [comment]
Thank you.
