### ISSUE TITLE
no difference in output for -v or --debug

### ISSUE THREAD

**Issue by CRCinAU** [markfasheh/duperemove#4]
After running through this for a while, I noticed that I seem to get stuck sometimes... When trying to debug this, I noticed there doesn't seem to be any difference in printed output between using:
$ duperemove -r /path/to/dedupe
$ duperemove -r -v /path/to/dedupe
$ duperemove -r -v --debug /path/to/dedupe

I'm still trying to run through (may just be impatience), I'm wondering if there should be some kind of progress bar option to show that something is still happening? Maybe a [x files examined] or similar?

I've been letting duperemove run for 20+ minutes and seen 100% CPU usage - but no obvious signs of it still doing anything - making me believe it stalled out. (which I'm not sure is the case as yet)

**Comment by dominicraf** [comment]
markfasheh wrote:

> The story with compression right now is that duperemove doesn't detect those extents. If it submits them to kernel, the kernel will just ignore the compressed extent and you won't get any dedupe. It shouldn't be too hard to make duperemove ignore compressed extents in the future though.

Can I just clarify this? If I am using compression (lzo, as it happens) and then apply deduperemove, will I get no deduplification benefits in respect of any compressed extents? That would be a big shame...

**Comment by markfasheh** [comment]
No right now we don't dedupe compressed extents (this is actually a kernel thing). Closing this bug btw.

**Comment by kdave** [comment]
The EXTENT_SAME ioctl works on compressed extents, same as CLONE_RANGE that's the actual implementation. A user reports that his custom dedup utility works fine with compressed files, so I'd expect the same should work in dupremove.
