### ISSUE TITLE
write-hashes and read-hashes with delay inbetween?

### ISSUE THREAD

**Issue by FloGa** [markfasheh/duperemove#49]
Hi,

this is just a question, not a bug since I haven't tried it yet.

Is it safe to run duperemove with `--write-hashes`, then let some time pass and run it with `-d --read-hashes` afterwards? By "safe" I mean "does not overwrite or destroy modified files".

I'm thinking of a scenario, where I let it run with `--write-hashes` the one day and then run out of time to do the actual dedup. Like two days or so afterwards I finally get around to actually dedup the files, but some of them may of course have been modified or even deleted in the meanwhile. I am fully aware, that those modified files cannot be dedupped using `--read-hashes` with the hashfile, but at least I don't want them to be overwritten.

Is there any risk with this approach?

**Comment by clobrother** [comment]
Hi,
There is no risk, data are recheck by the kernel under lock, during deduplication
At worst, you will make useless but harmless ioctl with modified data

**Comment by FloGa** [comment]
As long as I keep my modified data, I can live with some useless calls. Thank you for your explanation!
