### ISSUE TITLE
Duperemove version 0.09.2 stuck during file hashing phase

### ISSUE THREAD

**Issue by Claes1981** [markfasheh/duperemove#53]
Hi,

Duperemove (version 0.09.2) always gets stuck in the middle of the file hashing phase when I use it. It consumes no CPU or disk IO after it is stuck, but it can be terminated by pressing Ctrl-C. If I use the same directory to dedupe and the same block size, it gets stuck on/after the same file each time.

How could I further debug this issue?

Claes

**Comment by clobrother** [comment]
Hum

What options are you using exactly ?
Do you reach this issue with a single thread ?
You know which file cause the issue, can you read it entirely ? (try something like cat file > /dev/null)

**Comment by Claes1981** [comment]
Hi

It does get stuck also with option --hash-threads=1, but then earlier (at an earlier file). 

It get stuck with all options that I have tried, among others:
duperemove -r -d  ./@OpenSUSE_original/var/
duperemove -r  ./@OpenSUSE_original/var/ 
duperemove -r -x -d ./@OpenSUSE_original/var/
duperemove -r -x -d -b 1024k ./@OpenSUSE_original/var/

The last file that is printed out during the hashing phase, is that the last successfully hashed file, or the currently processed file?
If currently proccessed file, the file it get stuck on in the examples above is:
./@OpenSUSE_original/var//tmp/kdecache-claes/http/ae270236a855efff63c820d37b596e502dcfc907
Result of the cat command:
"# cat ./@OpenSUSE_original/var//tmp/kdecache-claes/http/ae270236a855efff63c820d37b596e502dcfc907 > /dev/null
#"

**Comment by sulaweyo** [comment]
I can confirm that issue on a Ubuntu 14.04 VM. 
I ran 'duperemove -r -h  -b 16K --write-hashes=$HASHFILE --lookup-extents=yes $i' and it get's stuck pretty early. Same command works perfectly fine with 9.1.

**Comment by Claes1981** [comment]
Thanks for pointing out that it works with version 0.09.1, that version seems to work for me too! (I am currently doing a dedup with ongoing hash phase, and it is not stuck yet after about 260 000 files so far...)
Version 0.09.2 gets stuck both on Fedora 21 and OpenSUSE Tumbleweed on my multi-boot laptop.

**Comment by markfasheh** [comment]
My guess is that this bug was introduced with one of my backported fixes for v0.09.2. Specifically, commit https://github.com/markfasheh/duperemove/commit/51b28e943ee7ccaab287fd4591444e18f7432049 

I revered the commit in my https://github.com/markfasheh/duperemove/tree/issue%2353 branch, in case you want it while I figure out where exactly we're going wrong.

**Comment by KevinAAsh** [comment]
Hello,
The lockup issue is caused by an incorrect define in duperemove.c. 
#define	glib2_mutex_unlock	g_mutex_lock

Should be
#define	glib2_mutex_unlock	g_mutex_unlock

**Comment by mgorny** [comment]
@KevinAAsh, thanks for the diagnosis. I can confirm that this fixes the issue for me.

**Comment by Claes1981** [comment]
Thanks,
version 0.09.3 does not get stuck during the file hashing phase on my computer.
