### ISSUE TITLE
Several subvolumes and -x switch?

### ISSUE THREAD

**Issue by Claes1981** [markfasheh/duperemove#57]
Hi,

Is it somehow possible to dedupe several subvolumes in the same run, while also using the -x switch? For example:
duperemove -r -d -x ./path/subvolume1 ./path/subvolume2

I have a lot of snapshots made by Snapper at ./path/subvolume1/.snapshots/, and when I ran the command above without the -x switch, Duperemove had not even started the hashing phase after several days (just slowly growing RAM usage).

However, when I run the command above with the -x switch, only subvolume1 gets deduped, Duperemove skips subvolume2.

(exakt command:
duperemove -r  -h -v -b 1024k -x --write-hashes=OpenSUSE_hashes.dup  ./@OpenSUSE_original/ ./@OpenSUSE/.snapshots/2/snapshot/ ./@OpenSUSE/ ./@OpenSUSE_boot_grub2_x86_64-efi/ ./@OpenSUSE_home/ ./@OpenSUSE_home_original/ ./@OpenSUSE_var_log/ ./@OpenSUSE_var_spool/
)

As an alternative solution to the -x switch, one could exclude certain directories from the dedup, if that is possible somehow? E g excluding ./path/subvolume1/.snapshots/ in the example above.

**Comment by Claes1981** [comment]
I think @clobrother's idea in issue #11 of using a pipe could also help me with this issue. Maybe something like
find ./path/subvolume1 ./path/subvolume2 -xdev -type f | duperemove -d -
could work.
Unfortunately it seems like using a pipe does not work with stable version 0.09.3 of duperemove though.

**Comment by clobrother** [comment]
That patch (https://github.com/markfasheh/duperemove/commit/66ec34effdefe0ce5f9cf3db23c77d28a2780cdf) is not in the v0.9.3
Please, use v0.10-dev

**Comment by Claes1981** [comment]
Thanks for the advice, is v0.10-dev the same as the "master" branch?

**Comment by clobrother** [comment]
Yes

**Comment by the8472** [comment]
> As an alternative solution to the -x switch, one could exclude certain directories from the dedup

```bash
mkdir ~/rootfs
mount -B / ~/rootfs
duperemove -r ~/rootfs
```

bind-mount is not recursive, so as long as duperemove doesn't follow absolute symlinks back to the root that should work without `-x`. Mount namespaces + removing the mounts inside the namespace might work too.

**Comment by Claes1981** [comment]
Thanks @the8472 for the suggestion, I will try that. I can also confirm that 
"find /path/subvolume1 /path/subvolume2 -xdev -type f | duperemove -d -A --hashfile=duperemove_hash -"
works with now stable version 10 of Duperemove.

**Comment by markfasheh** [comment]
Btw, this is now default behavior for master branch  - we will stay on one FS and subvolumes no longer count as a separate filesystem.
