### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by torhve** [markfasheh/duperemove#60]
Got this crash with flags -dhr running version 413493cdaabd6c008e1c33b996a040765b220b5f    

Program terminated with signal SIGABRT, Aborted.    
    #0  0x00007f2438937267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
    55      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007f2438937267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
    #1  0x00007f2438938eca in __GI_abort () at abort.c:89
    #2  0x00007f243897ac53 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f2438a931a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007f2438982c69 in malloc_printerr (ptr=<optimized out>, str=0x7f2438a93270 "double free or corruption (fasttop)", action=1) at malloc.c:4965
    #4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
    #5  0x00007f243898689c in __GI___libc_free (mem=<optimized out>) at malloc.c:2950
    #6  0x0000000000405b9c in free_extent (t=0x4245480) at results-tree.c:37
    #7  0x00000000004063f7 in remove_extent (res=0x7fff917c9a20, extent=0x4245480) at results-tree.c:260
    #8  0x000000000040d726 in dedupe_extent_list (dext=0x42452f0, fiemap_bytes=0x7f243726fe28, kern_bytes=0x7f243726fe30) at run_dedupe.c:210
    #9  0x000000000040dc49 in dedupe_worker (dext=0x42452f0, counts=0x7fff917c99a0) at run_dedupe.c:364
    #10 0x00007f243930c2e8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #11 0x00007f243930b955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #12 0x00007f243847e6aa in start_thread (arg=0x7f2437270700) at pthread_create.c:333
    #13 0x00007f2438a08eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by markfasheh** [comment]
Hey is there any chance you can try this with latest master branch? I have a commit in the area (f7dc80da68d5176b0b4b143a44ef918d1067c3c5) which fixed a crash for us. Hopefully it fixed the same thing for you :)

Btw, does this reproduce often or was it something that happened only once?

**Comment by torhve** [comment]
It happened on every run.

Master works OK. I will close this issue.
