### ISSUE TITLE
Store checksums as xattr

### ISSUE THREAD

**Issue by mikaelfrykholm** [markfasheh/duperemove#62]
It would be nice to store the checksums as extended attributes with each file to speed up subsequent runs.

**Comment by markfasheh** [comment]
Thanks for the suggestion, I am working on something close to this but storing them in a database file. If you have any further interest you can check out the planned features page, for this one look for the item  called 'Store results of our search"

https://github.com/markfasheh/duperemove/wiki/Development-Tasks
