### ISSUE TITLE
Debian control files for packaging

### ISSUE THREAD

**Issue by LordGaav** [markfasheh/duperemove#65]
Hi,

I created a repo with debian control files to package the 0.10beta1 version for Ubuntu Trusty. I could not find another repo/PPA that had done this before, correct me if there is an official source for Debian/Ubuntu package of duperemove.

Check out the repo here: https://github.com/LordGaav/duperemove-debian and the PPA here: https://launchpad.net/~lordgaav/+archive/ubuntu/duperemove .

The control files are tested on Ubuntu 14.04, but should also work on recent versions for Debian. The packaging is quite minimal, most of the work went in specifying a working `watch` file and specifying the `copyright` file properly.. All the heavy lifting is done by the original `Makefile`.

**Comment by Nefelim4ag** [comment]
Its Cool, can you enable vivid and wily in ppa? (i just love bleeding edge _._)

**Comment by LordGaav** [comment]
Done, packages are being pushed as we speak.

**Comment by Nefelim4ag** [comment]
@LordGaav, Thanks =^.^=

**Comment by markfasheh** [comment]
Thanks for this - let me leave this note here to myself to link to these files somewhere in our docs.

**Comment by melodie11** [comment]
Hello, as of today there is still none. Thanks for your work!

**Comment by calestyo** [comment]
Since duperemove is now officially in Debian, this can be probably closed.

**Comment by LordGaav** [comment]
Very nice, although it will be some time before the package is available in Ubuntu / Debian stable.

In the mean time I've uploaded a new package to the PPA based on 0.10 for Trusty, Xenial and Yakkety.

**Comment by melodie11** [comment]
On Fri, 20 Jan 2017 05:09:47 -0800
Nick Douma <notifications@github.com> wrote:

> Very nice, although it will be some time before the package is available in Ubuntu /
> Debian stable.
> 
> In the mean time I've uploaded a new package to the PPA based on 0.10 for Trusty,
> Xenial and Yakkety.


This is very nice, thank you!

Best regards,
Mélodie
