### ISSUE TITLE
fiemap start offset doesn't get properly updated, causes infinite loop

### ISSUE THREAD

**Issue by ChliHug** [markfasheh/duperemove#66]
Commit b8e2df40f3893a229d496be9aab899bc5a1c9878 changed (fixed?) how the start offset for the fiemap request gets set, but there needed to be an additional change at the other end of the loop. The start offset for the next request, should a file have more than 292 extents, doesn't get properly updated and the while loop gets stuck in an infinite loop since it can't find the extent with the last flag.

To fix that, [line 630 in filerec.c](https://github.com/markfasheh/duperemove/blob/a0805e40fadb3655e9409a268c7c4a75f0136dc1/filerec.c#L630) has to be changed to this.

```c
		start = (fm_ext[i - 1].fe_logical +
```

**Comment by markfasheh** [comment]
Good catch, and thanks for the detailed bug report. I have a fix in the 'issue#66' branch of duperemove.git:

https://github.com/markfasheh/duperemove/tree/issue%2366

If you have time to give it a test please do so and report back here so I can commit it to master branch. Otherwise I'll give it a spin myself when I get the chance.

**Comment by markfasheh** [comment]
Sorry didn't mean to close the issue yet.

**Comment by ChliHug** [comment]
Yes, that fixed it.

I totally forgot to mention how I got the error. I'm playing around with Btrfs on Arch and I use the binaries and libraries as test files. After creating a snapshot, duperemove suddenly ate all the kernel time when it hit some files. I noticed it with libQt5WebKit.so.5.4.1 and libwireshark.so.5.0.5. You can get them from these packages:

[Arch qt5-webkit-5.4.1-9-i686 package](http://archlinux.my-universe.com/extra/os/i686/qt5-webkit-5.4.1-9-i686.pkg.tar.xz)
[Arch wireshark-cli-1.12.5-2-i686 package](http://archlinux.my-universe.com/community/os/i686/wireshark-cli-1.12.5-2-i686.pkg.tar.xz)

If you compress them (either with lzo or zlib) they have over 292 extents. At least they had for me.

**Comment by markfasheh** [comment]
Awesome, thanks for testing and the extra info.
