### ISSUE TITLE
Package sqlite3 was not found

### ISSUE THREAD

**Issue by bob3434** [markfasheh/duperemove#67]
I tried to compile on Debian and received the following message:
Package sqlite3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sqlite3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sqlite3' found

A Google search suggested that libsqlite3-dev is required. I installed it and it seems to have fixed the problem.

Perhaps you can list libsqlite3-dev in the requirements section of the readme.md

**Comment by markfasheh** [comment]
Thanks for pointing this out - I have updated the readme.md in master branch to reflect our new library requirement.
