### ISSUE TITLE
Fails to find duplicates in Bitcoin block storage

### ISSUE THREAD

**Issue by luke-jr** [markfasheh/duperemove#70]
Bitcoin block files are very simply formatted: <32-bit magic> <32-bit block size> <N-bytes block data>

They are sequentially stored without padding, except sometimes the file end is padded with zeros (it is preallocated).

Magic is either F9BEB4D9 or 0B110907 (testnet).

Is this something that can be deduplicated with btrfs?

**Comment by markfasheh** [comment]
It doesn't sound like your data set would have many duplicates at the block granularity. Btrfs (and duperemove by extension) is doing this in at least 4K chunks, and I don't see that kind of data as giving us many identical chunks of that size.

**Comment by luke-jr** [comment]
Yes, data is not aligned at all presently. What if we change that? Will duperemove "just work"?

**Comment by markfasheh** [comment]
Yeah it will just work of course assuming the data itself is duplicated. Does it happen often that you might have many kilobytes worth of identical information (4K minimum, 128K default) in your files?

**Comment by luke-jr** [comment]
As a developer, I often have many instances running, each with their own copies of blocks in essentially-random order.
