### ISSUE TITLE
hashstats broken

### ISSUE THREAD

**Issue by lpirl** [markfasheh/duperemove#75]
on master, `hashstats` dies with a floating point exception

**Comment by markfasheh** [comment]
Can you give me an example? It seems to do the right thing here.

**Comment by lpirl** [comment]
sure
<pre>
$ git clone https://github.com/markfasheh/duperemove.git
…
$ cd duperemove; make
… [no errors]
$ ./duperemove -rh --hashfile ../myhashfile.sqlite3 /tmp        
Error 13: Permission denied …
…
Warning: murmur3 support is experimental!
Using 128K blocks
Using hash: murmur3
Using 4 threads for file hashing phase
…
Bloom gave us 584 hashes as 'almost duplicate'
We stored 584 unique hashes
Total hashes: 3232
…
Simple read and compare of file data found 1 instances of extents that might benefit from deduplication.
…
$ ./hashstats ../myhashfile.sqlite3 
Warning: murmur3 support is experimental!
zsh: floating point exception  ./hashstats ../myhashfile.sqlite3
</pre>

**Comment by markfasheh** [comment]
ok that's weird, and your usage seems normal... any chance you could load it up in gdb and give me a backtrace?

**Comment by juliantaylor** [comment]
for me it occurs in hash_tree.c:253, file-size is 0, so the module throws.
The weird thing is that the size of the file in question is not 0.

**Comment by markfasheh** [comment]
Ok yeah I see that now, I'll have a patch shortly.

**Comment by markfasheh** [comment]
Alright, if you don't mind trying the latest master branch I'd appreciate it. It turned out to be two issues - we weren't loading size back from the dbfile and we weren't setting blocksize in hashstats.

**Comment by lpirl** [comment]
Works for me now, thanks!
