### ISSUE TITLE
could not compile in debian wheezy

### ISSUE THREAD

**Issue by mac-linux-free** [markfasheh/duperemove#77]
here is the error...

dbfile.o: In function `dbfile_set_modes':
/root/duperemove/dbfile.c:99: undefined reference to `sqlite3_errstr'
/root/duperemove/dbfile.c:105: undefined reference to `sqlite3_errstr'
dbfile.o: In function `dbfile_create':
/root/duperemove/dbfile.c:133: undefined reference to `sqlite3_errstr'
/root/duperemove/dbfile.c:140: undefined reference to `sqlite3_errstr'
dbfile.o: In function `dbfile_open':
/root/duperemove/dbfile.c:163: undefined reference to `sqlite3_errstr'
dbfile.o:/root/duperemove/dbfile.c:188: more undefined references to `sqlite3_errstr' follow
collect2: error: ld returned 1 exit status
make: *** [duperemove] Fehler 1

**Comment by mac-linux-free** [comment]
no idea? i need this for the weeekend :)

**Comment by mac-linux-free** [comment]
sorry wrong button

**Comment by juliantaylor** [comment]
I cannot reproduce this on my debian.
does `pkg-config --libs sqlite3` work?

**Comment by mac-linux-free** [comment]
yes it returns:

root@st-fs-23:~/duperemove# pkg-config --libs sqlite3
-lsqlite3
root@st-fs-23:~/duperemove#

**Comment by clobrother** [comment]
Please:
```dpkg -l libsqlite3-dev```

**Comment by juliantaylor** [comment]
is -lsqlite3 on the link command line?

**Comment by mac-linux-free** [comment]
root@st-fs-23:~/duperemove# dpkg -l libsqlite3-dev
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                          Version             Architektur         Beschreibung
+++-=============================-===================-===================-================================================================
ii  libsqlite3-dev                3.7.13-1+deb7u2     amd64               SQLite 3 development files

**Comment by clobrother** [comment]
@mac-linux-free ok, so you need to update that package to either jessie or wheezy-backport
v3.7.15 required

**Comment by mac-linux-free** [comment]
that is bad because the required package is not in wheezy-backport...and the jessie package has too many dependencies...so i need to upgrade to jessie?

**Comment by clobrother** [comment]
Owh
Please, add the jessie sources, configure apt to prefere wheezy package : 
```
:~] cat /etc/apt/apt.conf
APT::Default-Release "wheezy";
```

And give the output of : 
```
aptitude install libsqlite3-dev=3.8.7.1-1+deb8u1
```

**Comment by juliantaylor** [comment]
or you could just the remove sqlite3_errstr calls from the file, worst case you will have to look up what an integer error code means. But usually the calls shouldn't fail anyway.

**Comment by mac-linux-free** [comment]
not working ... could i compile libsqlite3-dev in wheezy ?

**Comment by markfasheh** [comment]
Try out my sqlite_errstr branch please, I tried to put in a bit of backwards compatibility around the sqlite3_errstr() calls but don't have a system to test it on so I'm gonna be relying on your feedback :)

Thanks

**Comment by mac-linux-free** [comment]
it compiles .. thank you

**Comment by markfasheh** [comment]
no problem, thanks for testing quickly :)

**Comment by spmetas** [comment]
Hello, I tried latest v0.11 and it does not compile with same sqlite3 error:
tmp/cch25jk4.o: In function `print_all_blocks':
/src/dedup/duperemove/hashstats.c:147: undefined reference to `sqlite3_errstr'
/tmp/cch25jk4.o: In function `prepare_statements':
/src/dedup/duperemove/hashstats.c:67: undefined reference to `sqlite3_errstr'
/src/dedup/duperemove/hashstats.c:77: undefined reference to `sqlite3_errstr'
/tmp/cch25jk4.o: In function `print_by_size':
/home/arunas/src/dedup/duperemove/hashstats.c:128: undefined reference to `sqlite3_errstr'
/tmp/cch25jk4.o: In function `prepare_statements':
/src/dedup/duperemove/hashstats.c:87: undefined reference to `sqlite3_errstr'

System debian wheezy 7.11.
