### ISSUE TITLE
[FAQ?]  What happens if the file content changes during dedupe?

### ISSUE THREAD

**Issue by Edoa** [markfasheh/duperemove#79]
As in subject, what happens?
Does the kernel re-verify it before merging extents?
Can I loose data?

Should this question be put in the FAQs?

Thanks

**Comment by matthiaskrgr** [comment]
````
Duperemove does not deduplicate the data itself : it informs the kernel that these extents are the same, and shall be deduped.
The kernel rechecks the data bit-by-bit, under lock, to prevent parallel access / changes on the target inodes and ensures data integrity & safety.
````
https://github.com/markfasheh/duperemove/wiki/Frequently-Asked-Questions#is-duperemove-safe--can-it-break-my-data-

**Comment by Edoa** [comment]
Sorry, completely missed that. 
Thank you 

P.S. I was looking at the FAQs in the source as suggested in README.md, maybe those should be updated?

**Comment by lpirl** [comment]
big +1 for referencing the wiki FAQ in `FAQ.md` or - even better - merge those two FAQs in either one. I totally missed that the first time too.

**Comment by markfasheh** [comment]
I would be fine with merging the two. The documentation in general needs some work.
