### ISSUE TITLE
Exclude Folder?

### ISSUE THREAD

**Issue by mac-linux-free** [markfasheh/duperemove#82]
How could I exclude a folder from recursive deduping?

In my main folder there is a folder called .snapshots which I want to be excluded from the dedup process.

Thanks in advance.

**Comment by mac-linux-free** [comment]
sorry for this issue...it was not fully clear that the -x switch solves this for me.

**Comment by Claes1981** [comment]
Hi,

It is perhaps also possible to use find and a pipe as @clobrother suggests in issue #11, with development branch of duperemove, to exclude specifik folders (and still dedupe over several subvolumes). I have not tested that yet, though.
