### ISSUE TITLE
Unable to run btrfs send after deduplication

### ISSUE THREAD

**Issue by mac-linux-free** [markfasheh/duperemove#87]
Sorry to open this again. This is still not fixed with kernel 4.1.2 and btrfs-progs 4.1. After an unsuccessful dedup:

Kernel processed data (excludes target files): 32.0G
Comparison of extent info shows a net change in shared extents of: 0.0

the send / receive does not work:

BTRFS error (device vdb): did not find backref in send_root. inode=17588, offset=1703936, disk_byte=20751888384 found extent=20751888384

I fixed send/receive again with a full balance. But how to dedup?

**Comment by shyblower** [comment]
+1

**Comment by markfasheh** [comment]
Regarding the btrfs error you're seeing during send, there isn't anything that duperemove is doing directly which would cause this behavior. My guess is that send is broken (again) or that the clone code (used in the kernel for dedupe) corrupted something on disk.

Have you asked about this on the btrfs list?

**Comment by markfasheh** [comment]
Ok I reopened the original issue, gonna close this as a dupe now.
