### ISSUE TITLE
duperemove on RAID

### ISSUE THREAD

**Issue by lapsio** [markfasheh/duperemove#94]
Has this been ever tested on btrfs native raid which by design should be redundant? (btrfs seems to still improperly handle inode addressees on raid56 at least scrub fix messages and read errors seem to return inodes improperly resolved by current btrfs inspect-internal)

**Comment by markfasheh** [comment]
I have not personally tested it.

> btrfs seems to still improperly handle inode addressees on raid56 at least scrub fix messages and > read errors seem to return inodes improperly resolved by current btrfs inspect-internal

Hmm, that all seems quite problematic isn't raid56 still considered experimental?

**Comment by lapsio** [comment]
It is, but it's awesome :D. If it wasn't tested then I'll try it on some less important data. The same question about compressed data - does it collide with btrfs compression in any way?

**Comment by markfasheh** [comment]
You should be good with compressed data if you're on a newer kernel, otherwise it'll just be silently ignored by the kernel.

**Comment by lapsio** [comment]
kernel 4.0 and 4.1 is enough?

**Comment by Anthony25** [comment]
Hi,
I'm using duperemove on a raid10 pool since a few months, and on raid1 before that, no problem with it ;)
