### ISSUE TITLE
Process hangs with 100% CPU usage

### ISSUE THREAD

**Issue by clara-j** [markfasheh/duperemove#96]
I have a backup folder where I place backups from multiple systems.  Due to this there are a lot of duplicate files.  In the past I have used rdfind to hardlink between duplicates to lower disk usage. I am now wanting to use the btrfs dedupe functionality to replace that but have been running into issues.

Details
kernel: Ubuntu 14.04 LTS - Linux FileServer 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
folder size: 2.7T
duperemove version: duperemove v0.10.beta1
last scrub passed without issue and it is a single drive with no mirroring

When I run the process on the whole folder it seems to run fine checksumming the files until ~98%.  It then hangs in the the middle of writing to the screen and then stops.  The CPU stays at 100% until I kill it.  I let it run once for 7 days and still nothing new ever written to the screen and datestamp on hash file also didn't change
example output on last line:
csum: dir1/file4       [4889/500000]
csum: dir1/file4       [488  -- This line is cut off

What I did then to work around this was do a dry run of rdfind to list all duplicates and save it to a file.  I then created a bash script to go through the results and run duperemove one by one of the set of duplciate files.  This seemed to work but then I seem to have it hang again on some files.  I would let the process run for over an hour and would not get past the following part.
Search completed with no errors.
Simple read and compare of file data found 1 instances of extents that might benefit from deduplication.
Start           Length          Filename (2 extents)
0.0     40.2M   file1
0.0     40.2M   dir\file2
Using 4 threads for dedupe phase

The issue is in both cases I don't see any errors on the screen or the logs so I am not sure what to report back.  Is there any way to get more debugging info?  I an running with -d but no additional details are printed during the hangs.

**Comment by clara-j** [comment]
Noticed after that there is now beta4.  I downloaded that and am running it against the whole directory to see if the issue still exists with this version.

**Comment by clara-j** [comment]
So far I have not been able to re-create the issue with the latest beta so I think it is fixed.

**Comment by mac-linux-free** [comment]
Sorry to ask. Is the latest beta the master branch?

**Comment by clara-j** [comment]
duperemove v0.10.beta4

**Comment by mac-linux-free** [comment]
duperemove v0.11-dev ? where do I find the version?
