### ISSUE TITLE
use gnu find

### ISSUE THREAD

**Issue by guni77** [markfasheh/duperemove#99]
I would like to use something like find -size -100M -size +1000M -print0 and pipe it directly into dupremove. I tried dupremove $(find ...), but this did not work. Not shure because of whitespaces or of the restriction of arguments. Maybe a nice feature. 
Thanks for the software

**Comment by clobrother** [comment]
Just dash it : 
```find .. | duperemove -```

**Comment by juliantaylor** [comment]
how about:

     find . -print0 | xargs -0 duperemove

**Comment by clara-j** [comment]
Yes use at dash.  Here is an example

find . -iname "*rar" | sudo duperemove -dh  -

**Comment by guni77** [comment]
thanks I did not think about that. :)  @juliantaylor thanks for the idear. With xargs -0 I guess every file will be processed individually and therefore I think no dupes cant be removed. The other solution is right what I searched for.

**Comment by juliantaylor** [comment]
no -0 means terminate by NULL instead of whitespace, the counterpart to -print0

**Comment by guni77** [comment]
sorry stupid me ;)

**Comment by guni77** [comment]
I got it working with xargs -0, the not with the dash
echo "22" |duperemove -dh -
Error 2: No such file or directory while stating file -. Skipping.

**Comment by guni77** [comment]
even not shure if the xargs -0 approach works, because the files are processed in batches automatically and therefore depending on directory structure not sorted so that all same files get into the same batch

**Comment by guni77** [comment]
now looks a litte complicate but I think this should do the trick, files sorted by size now, and therefore batches should roughly be all the files with similar size with few exceptions:
find . -type f  -name "*.wav" -print0 | xargs -0 ls -S |tr '\n' '\0' | xargs -0 duperemove -dh

**Comment by clobrother** [comment]
guni77 : does the 22 file exists ?
You may try 
```
ls | duperemove -dh -
```

With your last post, the problem is that duperemove will be run multiple time, each time with a subset of files. Thus, it won't be able to work on files that are not in the same subset : efficiency is greatly reduced.

**Comment by guni77** [comment]
ls |duperemove -dh -
Error 2: No such file or directory while stating file -. Skipping.
no does not work

**Comment by guni77** [comment]
also not lucky about the approach i now use this
 find . -type f \( -name "*.pdf" -o -name "*.txt" -o -name "*.doc" -o -name "*.rtf" \) -print0 | xargs -0  du -h | sort -rn | cut -f2 | tr '\n' '\0' | xargs -0 duperemove -dh
becae the above example did not sort the files as a whole

**Comment by guni77** [comment]
I think the - (dash) oprator is not implemented yet

**Comment by lpirl** [comment]
the [man page](https://github.com/markfasheh/duperemove/blob/master/duperemove.8) says: "`files` can refer to a list of regular files and directories or be
a hyphen (-) to read them from standard input."

**Comment by guni77** [comment]
yay use 0.9 becaut webpages says this is stable version, i was not shure about "master" repo in the end i will use this on my files - so can "master" be used on production?

**Comment by clobrother** [comment]
Owh, 0.10 is stable now
I just updated the README

**Comment by guni77** [comment]
yay :)
